<?php

use App\DescripcionTalento;
use Illuminate\Database\Seeder;

class DescripcionTalentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $descripcion=[
            ['talento_id'=>1,'descripcion'=>'Eres afectuoso y cercano con las personas.'],
            ['talento_id'=>1,'descripcion'=>'Haces sentir cómoda a la gente que está a tu alrededor.'],
            ['talento_id'=>1,'descripcion'=>'Las personas se sienten bien cuando están contigo.'],
            ['talento_id'=>1,'descripcion'=>'Sabes encontrar cosas que sean de interés para ti y para otras personas, por lo que tienes facilidad para establecer una relación.'],
            ['talento_id'=>1,'descripcion'=>'Eres cordial y amable.'],
            ['talento_id'=>2,'descripcion'=>'Tienes valores fuertes y duraderos. Eres una persona altruista, responsable, ética y espiritual.'],
            ['talento_id'=>2,'descripcion'=>'Le das a la vida un significado especial y te brinda satisfacción lo que haces por el prójimo.'],
            ['talento_id'=>2,'descripcion'=>'Ayudar a las personas es la base de tus relaciones.'],
            ['talento_id'=>2,'descripcion'=>'Te gusta hacer más de lo que debes: sobrepasas, con frecuencia, las expectativas de las personas.'],
            ['talento_id'=>2,'descripcion'=>'Te preocupas por satisfacer las necesidades de las personas y cumplir con sus requerimientos; nada te resulta un gran problema.'],
            ['talento_id'=>2,'descripcion'=>'Necesitas un trabajo que concuerde con tus valores y que sea gratificante.'],
            ['talento_id'=>3,'descripcion'=>'Te dejas llevar por sentimientos de ternura, compasión y afecto.'],
            ['talento_id'=>3,'descripcion'=>'Te puedes sentir emocionado o herido con facilidad.'],
            ['talento_id'=>3,'descripcion'=>'Sientes emociones con facilidad.'],
            ['talento_id'=>3,'descripcion'=>'Te dejas llevar por las emociones y, en ocasiones, puedes sentirte vulnerable.'],
            ['talento_id'=>4,'descripcion'=>'Percibes los afectos de las personas que te rodean.'],
            ['talento_id'=>4,'descripcion'=>'Eres capaz de observar el mundo con los ojos de los demás y compartes su perspectiva, aunque no estés de acuerdo con esta. Comprendes al prójimo. No necesariamente significa que los disculpes, sino que los comprendes.'],
            ['talento_id'=>4,'descripcion'=>'Al "ponerte en los zapatos" de otro, anticipas sus necesidades: encuentras las palabras y tonos adecuados para comunicarte con él y lo ayudas a que exprese lo que siente.'],
            ['talento_id'=>5,'descripcion'=>'Expresas lo que piensas y sientes, con respeto a los demás y a ti mismo.'],
            ['talento_id'=>5,'descripcion'=>'Te sientes libre de expresarte de la manera que requiere cada situación.'],
            ['talento_id'=>5,'descripcion'=>'Mantienes una comunicación madura: no agredes ni te sometes a la voluntad de los demás. Expresas tus convicciones y defiendes tus derechos.'],
            ['talento_id'=>5,'descripcion'=>'Comunicas tus ideas y sentimientos; defiendes tus derechos sin intención de herir o perjudicar.'],
            ['talento_id'=>5,'descripcion'=>'Eres abierto a las opiniones de otros y les das la misma importancia que a las propias.'],
            ['talento_id'=>5,'descripcion'=>'Aceptas que la postura de los demás no tiene por qué coincidir con la tuya y, aunque evitas los conflictos, expresas lo que piensas de forma directa y honesta.'],
            ['talento_id'=>6,'descripcion'=>'Valoras la diversidad: acoges a las personas que son diferentes a ti mismo.'],
            ['talento_id'=>6,'descripcion'=>'Estás dispuesto a establecer relaciones interpersonales con personas diferentes a ti.'],
            ['talento_id'=>6,'descripcion'=>'Eres inclusivo a la hora de organizar tus reuniones: te preocupas por las personas que parecen aisladas o excluidas.'],
            ['talento_id'=>6,'descripcion'=>'Encuentras, en cada persona, una característica individual que la distingue y aprecias interactuar con ella.'],
            ['talento_id'=>7,'descripcion'=>'Buscas resolver y minimizar conflictos y discusiones: para ti, no se gana nada con ellos.'],
            ['talento_id'=>7,'descripcion'=>'Cuando las personas a tu alrededor tienen diferentes puntos de vista, procuras enlazar lo que tienen en común. Promueves la armo'],
            ['talento_id'=>7,'descripcion'=>'Te sorprende el tiempo que pierde la gente cuando trata de imponer su punto de vista a los demás. Tú, por el contrario, armoniza'],
            ['talento_id'=>7,'descripcion'=>'Cuando otros argumentan sus ideas, notas cómo todas pueden dirigirse a un punto común.'],
            ['talento_id'=>8,'descripcion'=>'Escuchas a otros con mucho interés y ganas de ayudar: no comienzas hablando de ti mismo.'],
            ['talento_id'=>8,'descripcion'=>'Muestras interés en lo que los otros tienen que decir y en la manera en que lo dicen.'],
            ['talento_id'=>8,'descripcion'=>'Cuando las personas te hablan, te centras en ellos. Escuchas realmente lo que te están diciendo.'],
            ['talento_id'=>8,'descripcion'=>'No solo escuchas las palabras: tratas de captar el mensaje real detrás de ellas.'],
            ['talento_id'=>8,'descripcion'=>'Para ti, todo lo que dice una persona es importante y merece ser escuchado.'],
            ['talento_id'=>9,'descripcion'=>'Te gusta conocer personas nuevas y ayudar a que se lleven bien entre ellas.'],
            ['talento_id'=>9,'descripcion'=>'Los extraños no se sienten intimidados por ti; por el contrario, se sienten bien cuando están contigo.'],
            ['talento_id'=>9,'descripcion'=>'Te esmeras en saber los nombres de los demás, en hacerles preguntas y en encontrar cosas en común que construyan un vínculo.'],
            ['talento_id'=>9,'descripcion'=>'No rehúyes el iniciar una conversación. Siempre tienes algo que decir. Te resulta fácil romper el hielo.'],
            ['talento_id'=>9,'descripcion'=>'Cuando estableces un lazo con una persona, estás feliz de pasar a la siguiente conversación, porque quieres conocer a mucha gente.'],
            ['talento_id'=>9,'descripcion'=>'Para ti, los demás no son extraños, sino amigos potenciales.'],
            ['talento_id'=>10,'descripcion'=>'Le pones entusiasmo y energía a todos tus proyectos.'],
            ['talento_id'=>10,'descripcion'=>'Eres una persona vital, despierta y alerta.'],
            ['talento_id'=>11,'descripcion'=>'Buscas oportunidades para hacer negocio y ganar dinero.'],
            ['talento_id'=>11,'descripcion'=>'Piensas en proyectos que puedan convertirse en negocios rentables.'],
            ['talento_id'=>12,'descripcion'=>'Eres generoso con los elogios y las sonrisas; ves la parte positiva de las situaciones adversas.'],
            ['talento_id'=>12,'descripcion'=>'Te convences de que las cosas funcionarán bien en el futuro.'],
            ['talento_id'=>12,'descripcion'=>'Te mantienes positivo, incluso cuando las circunstancias se ponen más difíciles.'],
            ['talento_id'=>12,'descripcion'=>'Tu optimismo ayuda a que los demás no se sientan aburridos, presionados o tensos. Encuentras la manera de aligerar estas trabas.'],
            ['talento_id'=>12,'descripcion'=>'No te amilana que otras personas te consideren despreocupado. Tienes la convicción de que la vida es buena y que el trabajo puede ser entretenido, a pesar de los traspiés.'],
            ['talento_id'=>13,'descripcion'=>'Tienes decisión e iniciativa para sacar adelante proyectos nuevos que implican riesgos.'],
            ['talento_id'=>13,'descripcion'=>'Te gusta empezar proyectos nuevos y poner todo tu empeño para lograrlos.'],
            ['talento_id'=>13,'descripcion'=>'Te definen tus ganas de enfrentar lo desconocido para lograr grandes beneficios (frutos de la acción realizada) y también tu capacidad de trabajar frente a la incertidumbre. '],
            ['talento_id'=>13,'descripcion'=>'No temes cometer errores y, si los cometes, aprendes de ellos.'],
            ['talento_id'=>14,'descripcion'=>'Sacas adelante los proyectos y llevas a la práctica lo planificado. Superas obstáculos y cumples con los objetivos.'],
            ['talento_id'=>14,'descripcion'=>'Te gusta materializar los proyectos: no te quedas en las ideas.'],
            ['talento_id'=>15,'descripcion'=>'Afrontas y superas tus miedos y temores.'],
            ['talento_id'=>15,'descripcion'=>'Participas en actividades que te desafían, incluso cuando pueden asustarte o ponerte nervioso.'],
            ['talento_id'=>15,'descripcion'=>'Tienes una disposición a actuar, tal vez con miedo, en situaciones peligrosas. Siempre, sin embargo, evalúas los riesgos razonables para obtener o preservar algo que percibes como bueno.'],
            ['talento_id'=>15,'descripcion'=>'Entiendes el riesgo y aceptas las consecuencias de la acción; dominas el miedo.'],
            ['talento_id'=>16,'descripcion'=>'Te anticipas: observas las oportunidades y te adelantas para ganar ventaja.'],
            ['talento_id'=>16,'descripcion'=>'Atraviesas el “desorden” y escoges la mejor ruta.'],
            ['talento_id'=>16,'descripcion'=>'Tienes una perspectiva distinta del mundo, que te permite advertir patrones donde los demás ven solo complejidad.'],
            ['talento_id'=>16,'descripcion'=>'Consciente de estos patrones, interactúas en diferentes espacios. Sueles preguntarte: “¿Qué pasaría si esto sucediera?”'],
            ['talento_id'=>16,'descripcion'=>'Descartas los patrones que llevan a la resistencia o la confusión.'],
            ['talento_id'=>16,'descripcion'=>'Escoges siempre el camino más directo.'],
            ['talento_id'=>17,'descripcion'=>'Para ti, cada día comienza en cero y, al final del mismo, debes lograr algo tangible para sentirte bien. Esto ocurre en los días'],
            ['talento_id'=>17,'descripcion'=>'Necesitas, a menudo, de retroalimentación positiva.'],
            ['talento_id'=>17,'descripcion'=>'Disfrutas el desafío de trabajar en un problema, aunque signifique cargar con la responsabilidad personal del éxito o fracaso.'],
            ['talento_id'=>17,'descripcion'=>'Te gusta sentir que el resultado (éxito o fracaso) depende de tus acciones.'],
            ['talento_id'=>17,'descripcion'=>'No importa cuánto se necesite un día de descanso: si no consigues algún logro, te sientes insatisfecho.'],
            ['talento_id'=>17,'descripcion'=>'Tienes un “fuego interno” que te empuja a conseguir más. Luego de cada logro, ese fuego disminuye, pero rápidamente renace y te empuja al siguiente reto.'],
            ['talento_id'=>17,'descripcion'=>'Puedes trabajar largas jornadas sin llegar necesariamente al burn-out (síndrome del trabajador desgastado o del desgaste profesional)'],
            ['talento_id'=>18,'descripcion'=>'Te adelantas a los demás en formular propuestas y buscar soluciones.'],
            ['talento_id'=>18,'descripcion'=>'Te impacientas por comenzar una nueva acción.'],
            ['talento_id'=>18,'descripcion'=>'Te gusta tomar la iniciativa, pues solo la acción permite que las cosas sucedan: cuando tomas una decisión, actúas.'],
            ['talento_id'=>19,'descripcion'=>'Eres bueno para crear e inventar cosas.'],
            ['talento_id'=>19,'descripcion'=>'Eres bueno para resolver problemas de forma rápida y astuta.'],
            ['talento_id'=>20,'descripcion'=>'Puedes cambiar tu manera de actuar o de pensar para adaptarte a diferentes circunstancias o necesidades.'],
            ['talento_id'=>20,'descripcion'=>'Vives el momento: no ves el futuro como un destino fijo, sino como algo que se construye con las decisiones de hoy.'],
            ['talento_id'=>20,'descripcion'=>'Desarrollas planes, pero te adaptas a las situaciones, incluso si estas se alejan de tu plan original.'],
            ['talento_id'=>20,'descripcion'=>'No sufres por los cambios; más bien, los esperas, pues te gusta responder a las demandas de manera productiva.'],
            ['talento_id'=>21,'descripcion'=>'Promueves ideas y comportamientos originales, novedosos, sorpresivos e inusuales.'],
            ['talento_id'=>21,'descripcion'=>'Aplicas soluciones en ámbitos diferentes (por ejemplo, la casa y el trabajo).'],
            ['talento_id'=>21,'descripcion'=>'Te gusta diseñar y crear cosas que sean mejores que las que se han hecho antes.'],
            ['talento_id'=>21,'descripcion'=>'Observas las cosas desde una perspectiva distinta; te gusta pensar “fuera de la caja”.'],
            ['talento_id'=>21,'descripcion'=>'Tus ideas permiten que las cosas avancen.'],
            ['talento_id'=>22,'descripcion'=>'Tienes un deseo interno por nuevas experiencias y conocimientos.'],
            ['talento_id'=>22,'descripcion'=>'Estás abierto a lo nuevo y te orientas al futuro; es probable que disfrutes de resolver problemas.'],
            ['talento_id'=>22,'descripcion'=>'Estás motivacionalmente abierto a lo novedoso.'],
            ['talento_id'=>23,'descripcion'=>'Tomas decisiones en base a tus presentimientos, a los indicios y señales que percibes.'],
            ['talento_id'=>23,'descripcion'=>'Basas tus decisiones más en la intuición que en la lógica.'],
            ['talento_id'=>23,'descripcion'=>'Comprendes las cosas instantáneamente, sin necesidad de razonarlas.'],
            ['talento_id'=>23,'descripcion'=>'Sabes relacionar ese conocimiento o información con experiencias previas, aunque, por lo general, te resulta difícil explicar cómo llegas a una determinada conclusión.'],
            ['talento_id'=>24,'descripcion'=>'Te cuesta aceptar las reglas y convenciones porque necesitas hacer cosas que nadie más hace.'],
            ['talento_id'=>24,'descripcion'=>'Te aproximas a las situaciones de manera original e ingeniosa; luchas por presentar nuevas y diferentes aplicaciones.'],
            ['talento_id'=>25,'descripcion'=>'Imaginas el futuro e inspiras a otros con tu visión.'],
            ['talento_id'=>25,'descripcion'=>'Ves el camino más allá del horizonte.'],
            ['talento_id'=>25,'descripcion'=>'El futuro te fascina: lo proyectas, evalúas lo que ofrece y te encaminas hacia el mañana.'],
            ['talento_id'=>25,'descripcion'=>'Eres soñador: tienes una visión y la valoras.'],
            ['talento_id'=>25,'descripcion'=>'Cuando el presente es frustrante y la gente se muestra muy pragmática, acudes a tus proyecciones del futuro.'],
            ['talento_id'=>26,'descripcion'=>'Puedes reírte de ti mismo y encuentras el lado divertido de las situaciones.'],
            ['talento_id'=>26,'descripcion'=>'Te gusta hacer reír a los demás.'],
            ['talento_id'=>26,'descripcion'=>'Compartes, con las personas que te rodean, un espíritu alegre.'],
            ['talento_id'=>26,'descripcion'=>'Sabes hacer una broma, contar una historia que mejore los ánimos y ayudas a que las personas se relajen.'],
            ['talento_id'=>26,'descripcion'=>'Cuando las cosas son adversas, aminoras su gravedad.'],
            ['talento_id'=>26,'descripcion'=>'Los otros aprecian que seas una persona divertida; les gusta estar contigo.'],
            ['talento_id'=>27,'descripcion'=>'Amas aprender, cualquiera sea el tema que te interese.'],
            ['talento_id'=>27,'descripcion'=>'Te estimula más el proceso que el contenido o el resultado.'],
            ['talento_id'=>27,'descripcion'=>'Disfrutas el paso de la ignorancia al conocimiento.'],
            ['talento_id'=>27,'descripcion'=>'Te gusta aprender cosas nuevas.'],
            ['talento_id'=>27,'descripcion'=>'Te gusta emprender proyectos que te permitan aprender y desarrollar tus intereses.'],
            ['talento_id'=>28,'descripcion'=>'Te gusta  identificar los pasos a seguir y las etapas o periodos de trabajo.'],
            ['talento_id'=>28,'descripcion'=>'Asignas roles y responsabilidades; programas tareas y reconoces el objetivo fundamental de cada una.'],
            ['talento_id'=>29,'descripcion'=>'Empiezas los proyectos apenas los recibes.'],
            ['talento_id'=>29,'descripcion'=>'Disfrutas al terminar los proyectos mucho antes de la fecha límite.'],
            ['talento_id'=>29,'descripcion'=>'No te gusta lidiar con presiones de último minuto; por ello, inicias lo encomendado apenas lo recibes.'],
            ['talento_id'=>30,'descripcion'=>'Cuando trabajas en algún proyecto, profundizas en los detalles.'],
            ['talento_id'=>30,'descripcion'=>'Eres meticuloso al ejecutar un proyecto o tarea.'],
            ['talento_id'=>30,'descripcion'=>'Puedes desarrollar un tema e identificar sus partes hasta describirlas de manera específica.'],
            ['talento_id'=>30,'descripcion'=>'Adviertes, de inmediato, los errores e inconsistencias.'],
            ['talento_id'=>30,'descripcion'=>'Te gusta ser capaz de corregir los errores.'],
            ['talento_id'=>30,'descripcion'=>'Disfrutas corregir y completar los detalles pendientes.'],
            ['talento_id'=>30,'descripcion'=>'Te resulta importante prestar atención a los detalles.'],
            ['talento_id'=>31,'descripcion'=>'Controlas las distracciones y los impulsos para lograr la meta que te propones.'],
            ['talento_id'=>31,'descripcion'=>'Trabajas con rigor en lo que te planteas, llevando de la mejor manera las molestias y postergaciones que esto puede ocasionar.'],
            ['talento_id'=>31,'descripcion'=>'Actúas ordenada y perseverantemente para conseguir lo propuesto.'],
            ['talento_id'=>31,'descripcion'=>'Exiges orden y lineamientos para lograr con mayor rapidez los objetivos deseados.'],
            ['talento_id'=>32,'descripcion'=>'Te concentras en pocos proyectos, para cumplirlos con rigurosidad. Evitas dispersarte en otras actividades.'],
            ['talento_id'=>32,'descripcion'=>'Eres impaciente con los retrasos u obstáculos.'],
            ['talento_id'=>32,'descripcion'=>'Haces recordar al resto que, si algo no ayuda a caminar hacia la meta, no es importante ni merece inversión de tiempo.'],
            ['talento_id'=>32,'descripcion'=>'Ayudas a que los otros no divaguen y retomen el curso de acción.'],
            ['talento_id'=>33,'descripcion'=>'Programas las actividades de un proyecto para evitar sorpresas y cumplir con los objetivos y fechas previstas.'],
            ['talento_id'=>33,'descripcion'=>'Tienes habilidad para planear y planificar: tienes una aproximación metódica a lo que haces.'],
            ['talento_id'=>33,'descripcion'=>'Antes de emprender una tarea, te organizas, verificas los tiempos disponibles y evalúas los recursos que tienes.'],
            ['talento_id'=>33,'descripcion'=>'Te gusta saber que has cubierto las posibles sorpresas y eventualidades.'],
            ['talento_id'=>34,'descripcion'=>'Colocas las cosas en el lugar que les corresponde y te esfuerzas por mantenerlas así.'],
            ['talento_id'=>34,'descripcion'=>'Sabes dónde están las cosas.'],
            ['talento_id'=>34,'descripcion'=>'Necesitas que el mundo sea predecible y estructurado.'],
            ['talento_id'=>34,'descripcion'=>'Ante el caos de la vida, necesitas sentirte en control.'],
            ['talento_id'=>34,'descripcion'=>'Tu orden y tu organización te ayudan a ser eficiente en lo que haces.'],
            ['talento_id'=>34,'descripcion'=>'Sin llegar a la rigidez, el orden te permite cuidar el progreso y la productividad.'],
            ['talento_id'=>35,'descripcion'=>'Realizas un seguimiento cercano a los proyectos o tareas a tu cargo.'],
            ['talento_id'=>35,'descripcion'=>'Sigues el avance de los proyectos o tareas a tu cargo con meticulosidad.'],
            ['talento_id'=>36,'descripcion'=>'Organizas y diriges a las personas para lograr metas y objetivos.'],
            ['talento_id'=>36,'descripcion'=>'Fijada una meta, te preocupas en cómo alinear a los demás para cumplirla.'],
            ['talento_id'=>36,'descripcion'=>'Compartes tu punto de vista con otras personas, aunque confrontes sus posiciones: sabes que es la única manera de resolver dificultades y avanzar hacia la meta.'],
            ['talento_id'=>36,'descripcion'=>'Te gusta ser claro con los demás y dirigir a la gente, aunque a veces implique tomar riesgos.'],
            ['talento_id'=>37,'descripcion'=>'Eres bueno para dar razones/argumentos a favor o en contra de alguien o de algo.'],
            ['talento_id'=>37,'descripcion'=>'Elaboras argumentos y razones con facilidad para defender una posición específica.'],
            ['talento_id'=>38,'descripcion'=>'Tienes facilidad para convencer a las personas de hacer algo o de pensar de cierta manera.'],
            ['talento_id'=>38,'descripcion'=>'Tienes una persuasión eficaz para que otros cambien su manera de pensar.'],
            ['talento_id'=>38,'descripcion'=>'Elaboras nuevos argumentos para lo que quieres, eliges el lenguaje adecuado y planificas cómo convencer a los otros.'],
            ['talento_id'=>39,'descripcion'=>'Enseñas, aconsejas y ayudas a otros a ser mejores personas.'],
            ['talento_id'=>39,'descripcion'=>'Comprendes las necesidades y sentimientos de los otros; te preocupas por ayudarlos.'],
            ['talento_id'=>39,'descripcion'=>'Te relacionas con las preocupaciones de los otros: los reconfortas, ofreces tu consejo y ayudas con amabilidad; eres amigable y atento con las personas.'],
            ['talento_id'=>40,'descripcion'=>'Escribes de manera clara, precisa y efectiva.'],
            ['talento_id'=>40,'descripcion'=>'Eres bueno con los textos escritos.'],
            ['talento_id'=>40,'descripcion'=>'Tienes facilidad para la lectura, la comprensión y la expresión escrita.'],
            ['talento_id'=>40,'descripcion'=>'Tienes habilidad para comunicar ideas y lograr metas por medios lingüísticos.'],
            ['talento_id'=>40,'descripcion'=>'Te gusta jugar con las palabras y disfrutas del lenguaje escrito.'],
            ['talento_id'=>40,'descripcion'=>'Escribir te ayuda a aclarar el pensamiento y ser más preciso.'],
            ['talento_id'=>40,'descripcion'=>'Te gusta escribir textos para que otros los lean.'],
            ['talento_id'=>40,'descripcion'=>'Te gusta narrar, leer, jugar con rimas, entre otros ejercicios de redacción.'],
            ['talento_id'=>41,'descripcion'=>'Estás actualizado, al día de lo que pasa en el país o en el mundo.'],
            ['talento_id'=>41,'descripcion'=>'Buscas diversas fuentes de información sobre lo que sucede en el país o en el mundo: periódicos, web, libros, entre otros.'],
            ['talento_id'=>42,'descripcion'=>'Te encargas de una situación para llegar a un acuerdo o una solución.'],
            ['talento_id'=>42,'descripcion'=>'Tienes facilidad para tratar con las personas y para establecer pactos.'],
            ['talento_id'=>43,'descripcion'=>'Expresas ideas, en forma oral, con claridad, facilidad y entusiasmo. Captas la atención de tu audiencia (así sea una o muchas personas)'],
            ['talento_id'=>43,'descripcion'=>'Te gusta explayarte, describir, ser anfitrión y hablar en público.'],
            ['talento_id'=>43,'descripcion'=>'Te gusta darle vida a los hechos a través de las palabras.'],
            ['talento_id'=>43,'descripcion'=>'Te gusta convertir los eventos en historias: recurres a ejemplos y metáforas.'],
            ['talento_id'=>43,'descripcion'=>'Requieres de ideas, eventos, productos, descubrimientos y lecciones para sobrevivir con tal de atraer la atención y capturarla.'],
            ['talento_id'=>44,'descripcion'=>'Hablas y actúas con muchos gestos y expresiones.'],
            ['talento_id'=>44,'descripcion'=>'Manifiestas vívidamente lo que piensas o sientes.'],
            ['talento_id'=>44,'descripcion'=>'Gesticulas: recurres a muecas, palabras y/o expresiones para reflejar lo que sientes.'],
            ['talento_id'=>45,'descripcion'=>'Actúas de acuerdo a las ideas que expresas.'],
            ['talento_id'=>45,'descripcion'=>'Te gusta hacer lo que predicas: tus actos reflejan tus palabras.'],
            ['talento_id'=>46,'descripcion'=>'Tienes facilidad con los números y las matemáticas.'],
            ['talento_id'=>46,'descripcion'=>'Buscas información fáctica que te provea de data.'],
            ['talento_id'=>46,'descripcion'=>'Te gusta sistematizar la información que encuentras.'],
            ['talento_id'=>46,'descripcion'=>'Le encuentras sentido a los cuadros y las cifras y estableces relaciones entre las cantidades.'],
            ['talento_id'=>46,'descripcion'=>'Memorizas códigos, cifras y años, entre otros datos numéricos.'],
            ['talento_id'=>47,'descripcion'=>'Eres cuidadoso y te gusta pensar.'],
            ['talento_id'=>47,'descripcion'=>'Para hacer algo, necesitas una razón.'],
            ['talento_id'=>47,'descripcion'=>'El mundo es, para ti, un lugar impredecible: sabes que el mundo, aunque aparente ser ordenado, plantea riesgos que se deben identificar, evaluar y reducir.'],
            ['talento_id'=>47,'descripcion'=>'Eres serio y te acercas a la vida con cautela. Te gusta planear las cosas y seleccionas cuidadosamente a tus amigos.'],
            ['talento_id'=>47,'descripcion'=>'Te gusta la actividad mental y pensar las cosas con calma; eres introspectivo y disfrutas tu tiempo a solas.'],
            ['talento_id'=>48,'descripcion'=>'Eres equilibrado y sereno.'],
            ['talento_id'=>48,'descripcion'=>'No te alteras ni reaccionas de manera violenta o pasional ante situaciones difíciles.'],
            ['talento_id'=>48,'descripcion'=>'Mantienes la calma casi sin esfuerzo.'],
            ['talento_id'=>48,'descripcion'=>'Mantienes la compostura en diferentes circunstancias y las personas te admiran por esta cualidad.'],
            ['talento_id'=>49,'descripcion'=>'Cuestionas y te anticipas a los problemas.'],
            ['talento_id'=>49,'descripcion'=>'Evalúas las situaciones a través de la observación, la  experiencia y el razonamiento.'],
            ['talento_id'=>49,'descripcion'=>'Procuras entender y evaluar los argumentos: distinguir lo razonable de lo ilógico y lo verdadero de lo falso.'],
            ['talento_id'=>50,'descripcion'=>'Te gusta aprender por ti mismo.'],
            ['talento_id'=>50,'descripcion'=>'Buscas los medios para aprender sin ninguna tutela.'],
            ['talento_id'=>50,'descripcion'=>'Eres autónomo para aprender lo que te interesa.'],
            ['talento_id'=>51,'descripcion'=>'Estás actualizado y te gusta conocer los últimos avances de una ciencia determinada.'],
            ['talento_id'=>51,'descripcion'=>'Te apasiona un área de interés (una ciencia específica) y profundizas en los últimos avances.'],
            ['talento_id'=>52,'descripcion'=>'Disfrutas aquello que te permite aprender, crecer y desarrollarte.'],
            ['talento_id'=>52,'descripcion'=>'Te gusta estar inmerso en el proceso de aprender.'],
            ['talento_id'=>52,'descripcion'=>'Buscas oportunidades que te permitan desarrollar tus capacidades e intereses.'],
            ['talento_id'=>52,'descripcion'=>'Te emocionan los nuevos hechos, los primeros esfuerzos de llevar a la práctica lo aprendido, la adquisición de confianza progresiva, esto es lo que le atrae.'],
            ['talento_id'=>52,'descripcion'=>'Te gusta involucrarte en aquello que te permite aprender algo nuevo: clases de piano, de algún idioma, de cocina, o profundizar en diferentes temas que capten su interés.'],
            ['talento_id'=>53,'descripcion'=>'Te gusta que las afirmaciones tengan pruebas: cuando alguien sostiene algo, debe demostrarte que es verdad.'],
            ['talento_id'=>53,'descripcion'=>'Necesitas datos que den valor a las ideas.'],
            ['talento_id'=>53,'descripcion'=>'Te gusta entender cómo algunos modelos afectan a otros, cómo se combinan, cuáles son sus resultados y cómo estos resultados encajan en la situación que enfrentas.'],
            ['talento_id'=>53,'descripcion'=>'Te gusta escarbar hasta encontrar la raíz: que las causas se revelen de manera lógica y rigurosa.'],
            ['talento_id'=>54,'descripcion'=>'Buscas información en diversas fuentes para comprender algo que no conoces.'],
            ['talento_id'=>54,'descripcion'=>'Eres perceptivo y extraordinariamente observador: tu curiosidad es permanente y tu mente se encuentra alerta.'],
            ['talento_id'=>54,'descripcion'=>'Formulas preguntas adecuadas; te concentras y enfocas en lo que llama tu atención y puedes predecir el desenlace de una cadena de eventos.'],
            ['talento_id'=>54,'descripcion'=>'Te gusta aprender y te entusiasma poseer conocimientos: puedes convertirte en experto en algún campo.'],
            ['talento_id'=>54,'descripcion'=>'Puedes desarrollar ideas muy valiosas.'],
            ['talento_id'=>55,'descripcion'=>'Tienes facilidad para pensar en imágenes.'],
            ['talento_id'=>55,'descripcion'=>'Te resulta fácil transformar las ideas en imágenes.'],
            ['talento_id'=>56,'descripcion'=>'Imaginas figuras: puedes rotarlas y cambiarlas de posición mentalmente.'],
            ['talento_id'=>57,'descripcion'=>'Tienes facilidad para aprender nuevos idiomas.'],
            ['talento_id'=>57,'descripcion'=>'Cuando entras en contacto con otro idioma, te resulta fácil entenderlo y/o hablarlo.'],
            ['talento_id'=>58,'descripcion'=>'Disfrutas de lo bello, de aquello que es realizado con una noción estética.'],
            ['talento_id'=>59,'descripcion'=>'Tienes facilidad para la música.'],
            ['talento_id'=>59,'descripcion'=>'Asimilas el ritmo de la música sin mayor complicación.'],
            ['talento_id'=>60,'descripcion'=>'Manejas con facilidad temas de biología, química o física.'],
            ['talento_id'=>61,'descripcion'=>'Disfrutas y aprecias la belleza.'],
            ['talento_id'=>62,'descripcion'=>'Tienes facilidad para las actividades que requieren de motricidad fina.']
        ];

        DescripcionTalento::insert($descripcion);
    }
}
