<?php

use Illuminate\Database\Seeder;
use App\Pregunta;

class PreguntaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $intereses=[
            ['carrera_id'=>1,'tipo_encuesta_id'=>1,'nombre'=> 'Administrar una empresa, hotel o fábrica.'],
            ['carrera_id'=>2,'tipo_encuesta_id'=>1,'nombre'=> 'Cuidar que las semillas produzcan mejores frutos y vegetales.'],
            ['carrera_id'=>3,'tipo_encuesta_id'=>1,'nombre'=> 'Representar un personaje de teatro, cine o televisión.'],
            ['carrera_id'=>4,'tipo_encuesta_id'=>1,'nombre'=> 'Conducir programas de televisión o de radio.'],
            ['carrera_id'=>5,'tipo_encuesta_id'=>1,'nombre'=> 'Dirigir la construcción de edificios o carreteras.'],
            ['carrera_id'=>6,'tipo_encuesta_id'=>1,'nombre'=> 'Crear nuevas recetas de comidas.'],
            ['carrera_id'=>7,'tipo_encuesta_id'=>1,'nombre'=> 'Entrenar a deportistas.'],
            ['carrera_id'=>8,'tipo_encuesta_id'=>1,'nombre'=> 'Diseñar casas, parques o centros comerciales.'],
            ['carrera_id'=>9,'tipo_encuesta_id'=>1,'nombre'=> 'Definir los precios más competitivos para un producto en el mercado.'],
            ['carrera_id'=>10,'tipo_encuesta_id'=>1,'nombre'=> 'Crear software de simulación, animación o entretenimiento.'],
            ['carrera_id'=>11,'tipo_encuesta_id'=>1,'nombre'=> 'Defender los derechos de las personas.'],
            ['carrera_id'=>12,'tipo_encuesta_id'=>1,'nombre'=> 'Evaluar la satisfacción del cliente con un negocio o producto.'],
            ['carrera_id'=>13,'tipo_encuesta_id'=>1,'nombre'=> 'Armar y desarmar máquinas y equipos para entender cómo funcionan.'],
            ['carrera_id'=>14,'tipo_encuesta_id'=>1,'nombre'=> 'Extraer los minerales de un yacimiento.'],
            ['carrera_id'=>15,'tipo_encuesta_id'=>1,'nombre'=> 'Mejorar las técnicas de enseñanza de los cursos.'],
            ['carrera_id'=>16,'tipo_encuesta_id'=>1,'nombre'=> 'Tratar las enfermedades físicas de las personas.'],
            ['carrera_id'=>17,'tipo_encuesta_id'=>1,'nombre'=> 'Escuchar y entender los problemas de las personas.'],
            ['carrera_id'=>18,'tipo_encuesta_id'=>1,'nombre'=> 'Traducir textos considerando su contexto cultural.'],
            ['carrera_id'=>19,'tipo_encuesta_id'=>1,'nombre'=> 'Promover el turismo de un país o una región.'],
            ['carrera_id'=>1,'tipo_encuesta_id'=>1,'nombre'=> 'Planificar las acciones de una empresa, hotel o fábrica para lograr sus objetivos.'],
            ['carrera_id'=>2,'tipo_encuesta_id'=>1,'nombre'=> 'Procesar cereales para que las personas los puedan consumir.'],
            ['carrera_id'=>3,'tipo_encuesta_id'=>1,'nombre'=> 'Comunicar ideas y sentimientos a través de la música, la actuación o el baile.'],
            ['carrera_id'=>4,'tipo_encuesta_id'=>1,'nombre'=> 'Producir películas de cine o programas de radio o televisión.'],
            ['carrera_id'=>5,'tipo_encuesta_id'=>1,'nombre'=> 'Calcular los materiales necesarios para la construcción de un puente.'],
            ['carrera_id'=>6,'tipo_encuesta_id'=>1,'nombre'=> 'Preparar diversos platos de comida.'],
            ['carrera_id'=>7,'tipo_encuesta_id'=>1,'nombre'=> 'Dirigir la preparación de los deportistas.'],
            ['carrera_id'=>8,'tipo_encuesta_id'=>1,'nombre'=> 'Crear combinaciones armoniosas de colores.'],
            ['carrera_id'=>9,'tipo_encuesta_id'=>1,'nombre'=> 'Llevar un registro de los ingresos y gastos de una empresa.'],
            ['carrera_id'=>10,'tipo_encuesta_id'=>1,'nombre'=> 'Diseñar páginas web de intercambio de videos y de información personal.'],
            ['carrera_id'=>11,'tipo_encuesta_id'=>1,'nombre'=> 'Orientar a las personas utilizando normas o leyes.'],
            ['carrera_id'=>12,'tipo_encuesta_id'=>1,'nombre'=> 'Crear productos de acuerdo a las necesidades del consumidor.'],
            ['carrera_id'=>13,'tipo_encuesta_id'=>1,'nombre'=> 'Armar redes de comunicación entre las computadoras.'],
            ['carrera_id'=>14,'tipo_encuesta_id'=>1,'nombre'=> 'Localizar minas o yacimientos petroleros.'],
            ['carrera_id'=>15,'tipo_encuesta_id'=>1,'nombre'=> 'Dar clases utilizando métodos que aseguren el aprendizaje de los alumnos.'],
            ['carrera_id'=>16,'tipo_encuesta_id'=>1,'nombre'=> 'Asesorar a las personas para que tengan una alimentación saludable.'],
            ['carrera_id'=>17,'tipo_encuesta_id'=>1,'nombre'=> 'Orientar a las personas para que resuelvan sus problemas personales.'],
            ['carrera_id'=>18,'tipo_encuesta_id'=>1,'nombre'=> 'Adaptar los diálogos de las películas para que sean dobladas.'],
            ['carrera_id'=>19,'tipo_encuesta_id'=>1,'nombre'=> 'Mostrar nuevos lugares turísticos.'],
            ['carrera_id'=>1,'tipo_encuesta_id'=>1,'nombre'=> 'Manejar las importaciones o exportaciones de una empresa, hotel o fábrica.'],
            ['carrera_id'=>2,'tipo_encuesta_id'=>1,'nombre'=> 'Sembrar y cultivar frutos o vegetales.'],
            ['carrera_id'=>3,'tipo_encuesta_id'=>1,'nombre'=> 'Participar de un grupo artístico (orquesta, grupo musical, elenco de actores).'],
            ['carrera_id'=>4,'tipo_encuesta_id'=>1,'nombre'=> 'Realizar reportajes periodísticos.'],
            ['carrera_id'=>5,'tipo_encuesta_id'=>1,'nombre'=> 'Construir un edificio.'],
            ['carrera_id'=>6,'tipo_encuesta_id'=>1,'nombre'=> 'Preparar pasteles, dulces o postres.'],
            ['carrera_id'=>7,'tipo_encuesta_id'=>1,'nombre'=> 'Asesorar a los deportistas para mejorar su rendimiento.'],
            ['carrera_id'=>8,'tipo_encuesta_id'=>1,'nombre'=> 'Aplicar el arte a objetos funcionales (muebles, ropa, adornos, etc.).'],
            ['carrera_id'=>9,'tipo_encuesta_id'=>1,'nombre'=> 'Supervisar que los ingresos y gastos de una empresa estén de acuerdo con lo planeado.'],
            ['carrera_id'=>10,'tipo_encuesta_id'=>1,'nombre'=> 'Crear aplicaciones para celulares o tablets.'],
            ['carrera_id'=>11,'tipo_encuesta_id'=>1,'nombre'=> 'Defender a una persona analizando los hechos.'],
            ['carrera_id'=>12,'tipo_encuesta_id'=>1,'nombre'=> 'Persuadir a las personas para que compren productos o servicios de una empresa.'],
            ['carrera_id'=>13,'tipo_encuesta_id'=>1,'nombre'=> 'Reparar motores y equipos mecánicos o electrónicos.'],
            ['carrera_id'=>14,'tipo_encuesta_id'=>1,'nombre'=> 'Descubrir minerales valiosos en lugares recónditos.'],
            ['carrera_id'=>15,'tipo_encuesta_id'=>1,'nombre'=> 'Evaluar el rendimiento de los alumnos.'],
            ['carrera_id'=>16,'tipo_encuesta_id'=>1,'nombre'=> 'Preservar la salud integral de las personas.'],
            ['carrera_id'=>17,'tipo_encuesta_id'=>1,'nombre'=> 'Apoyar a las personas para que desarrollen su máximo potencial.'],
            ['carrera_id'=>18,'tipo_encuesta_id'=>1,'nombre'=> 'Traducir conferencias o entrevistas.'],
            ['carrera_id'=>19,'tipo_encuesta_id'=>1,'nombre'=> 'Brindar servicios a los turistas.'],
            ['carrera_id'=>1,'tipo_encuesta_id'=>1,'nombre'=> 'Negociar acuerdos con empresas nacionales o internacionales.'],
            ['carrera_id'=>2,'tipo_encuesta_id'=>1,'nombre'=> 'Supervisar la producción de alimentos.'],
            ['carrera_id'=>3,'tipo_encuesta_id'=>1,'nombre'=> 'Producir espectáculos artísticos.'],
            ['carrera_id'=>4,'tipo_encuesta_id'=>1,'nombre'=> 'Transmitir ideas por medios audiovisuales.'],
            ['carrera_id'=>5,'tipo_encuesta_id'=>1,'nombre'=> 'Supervisar la construcción de un centro comercial'],
            ['carrera_id'=>6,'tipo_encuesta_id'=>1,'nombre'=> 'Presentar los platos de comida de forma atractiva.'],
            ['carrera_id'=>7,'tipo_encuesta_id'=>1,'nombre'=> 'Diseñar estrategias para ganar competencias deportivas.'],
            ['carrera_id'=>8,'tipo_encuesta_id'=>1,'nombre'=> 'Realizar dibujos en perspectiva.'],
            ['carrera_id'=>9,'tipo_encuesta_id'=>1,'nombre'=> 'Analizar los efectos de los cambios económicos sobre las empresas.'],
            ['carrera_id'=>10,'tipo_encuesta_id'=>1,'nombre'=> 'Diseñar antivirus o protectores de información personal de las computadoras.'],
            ['carrera_id'=>11,'tipo_encuesta_id'=>1,'nombre'=> 'Facilitar que las personas lleguen a un acuerdo en términos legales.'],
            ['carrera_id'=>12,'tipo_encuesta_id'=>1,'nombre'=> 'Diseñar estrategias para ampliar el mercado de los productos o servicios de una empresa.'],
            ['carrera_id'=>13,'tipo_encuesta_id'=>1,'nombre'=> 'Realizar proyectos de robótica.'],
            ['carrera_id'=>14,'tipo_encuesta_id'=>1,'nombre'=> 'Dirigir la búsqueda de yacimientos petroleros.'],
            ['carrera_id'=>15,'tipo_encuesta_id'=>1,'nombre'=> 'Preparar materiales para la enseñanza.'],
            ['carrera_id'=>16,'tipo_encuesta_id'=>1,'nombre'=> 'Rehabilitar a personas adictas (a las drogas, videojuegos, etc.).'],
            ['carrera_id'=>17,'tipo_encuesta_id'=>1,'nombre'=> 'Evaluar las capacidades de las personas para conocerlas en profundidad.'],
            ['carrera_id'=>18,'tipo_encuesta_id'=>1,'nombre'=> 'Traducir las conversaciones de las películas.'],
            ['carrera_id'=>19,'tipo_encuesta_id'=>1,'nombre'=> 'Coordinar los servicios turísticos ofrecidos a un grupo de personas.'],
            ['carrera_id'=>16,'tipo_encuesta_id'=>1,'nombre'=> 'Corregir las alteraciones en la posición de los dientes para mejorar la sonrisa de las personas.'],
            ['carrera_id'=>16,'tipo_encuesta_id'=>1,'nombre'=> 'Tratar las limitaciones funcionales y discapacidades de las personas.'],
            ['carrera_id'=>20,'tipo_encuesta_id'=>1,'nombre'=> 'Cuidar la salud física de los animales.'],
            ['carrera_id'=>20,'tipo_encuesta_id'=>1,'nombre'=> 'Crear tratamientos médicos en bienestar de los animales.'],
            ['carrera_id'=>20,'tipo_encuesta_id'=>1,'nombre'=> 'Investigar sobre temas de producción de animales (pollos, cerdos, vacas).'],
            ['carrera_id'=>20,'tipo_encuesta_id'=>1,'nombre'=> 'Realizar estudios sobre distintas especies animales (animales exóticos).']
        ];

        Pregunta::insert($intereses);

        $temperamentos=[
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Tengo muchos amigos por lo que frecuento diversos grupos de amistades. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me relaciono con pocos amigos, los cuales son muy cercanos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Soy bueno generando conversaciones casuales o ligeras en una reunión. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me es difícil establecer conversaciones casuales o ligeras en una reunión. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En reuniones sociales me es fácil conversar con personas que no conozco. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En reuniones sociales me es difícil conversar con personas que no conozco. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me es fácil hacer nuevos amigos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me es difícil hacer nuevos amigos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Tengo una gran cantidad de amigos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Tengo un grupo pequeño de amigos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En reuniones sociales, suelo dar mis opiniones con facilidad. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En reuniones sociales, me cuesta dar mis opiniones. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando estoy con otras personas, tiendo a ser muy conversador. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando estoy con otras personas, soy uno de los que menos conversa. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En reuniones sociales, suelo compartir las cosas que me pasan. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En reuniones sociales, hablo poco de las cosas que me pasan. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando estoy con otras personas, me es difícil mantenerme en silencio (por largos periodos de tiempo) (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando estoy con otras personas, prefiero estar en silencio y escuchar lo que otros dicen (por largos periodos de tiempo). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando comparto con otros mis puntos de vista, me resulta fácil que las personas se entusiasmen por los temas que me interesan. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando comparto con otros mis puntos de vista, me resulta difícil involucrar a las personas en los temas que me interesan. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por mi manera de ser, la gente se da cuenta de mis emociones y los temas que me interesan. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por mi manera de ser, la gente se da cuenta de que soy una persona reservada pues evito compartir mis emociones con otras personas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Tiendo a usar las manos, enfatizar las palabras y usar gestos al hablar. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando hablo, uso pocos gestos y mantengo un mismo tono de voz. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando alguien me conoce, se da cuenta fácilmente cómo soy (mi manera de ser). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando alguien me conoce, le es difícil darse cuenta cómo soy (mi manera de ser). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento cómodo en ambientes con mucha gente, ruido y movimiento (ejemplo: centro comercial). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Evito ir a lugares donde hay mucha gente, bulla y movimiento (ejemplo: centro comercial). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento más cómodo en ambientes calmados y tranquilos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento más cómodo en ambientes con mucho movimiento. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento cómodo con el ruido de los ambientes donde hay mucha gente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me incomoda la bulla de los ambientes donde hay mucha gente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento cómodo en ambientes con poca gente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento cómodo en ambientes donde hay mucha gente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En una decisión, confío más en mí intuición que en la información que reciba (hechos, cifras, datos). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Al tomar una decisión, confío más en la información recogida (hechos, cifras, datos) que en mi intuición. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Prefiero decidir por intuición en vez de analizar tanto. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Prefiero tomar más tiempo analizando que decidir en base a mi intuición. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando me explican algo, prefiero que me expliquen los hechos en detalle para luego formarme una idea de la figura completa. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando me explican algo, prefiero que me expliquen la figura completa y luego entender los hechos en detalle. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Pienso que la mejor manera de entregar un plan, es presentarlo con la información a detalle. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Pienso que la mejor manera de entregar un plan, es presentando las grandes ideas sin entrar a tanto detalle. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Al tomar una decisión, considero más importante la lógica y la razón antes que los sentimientos de las personas involucradas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Para tomar una decisión, considero más importante los sentimientos de las personas involucradas antes que la lógica y la razón. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Pienso que una de mis fortalezas es estar constantemente preocupado del impacto que tienen mis decisiones sobre las personas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Pienso que una de mis fortalezas es usar la lógica y la razón en mis decisiones aunque esta decisión pueda afectar emocionalmente a algunas personas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Si tuviera que sacar a una persona de mi grupo de trabajo, siento que podría hacerlo pero me costaría mucho por los sentimientos de las personas involucradas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Si tuviera que sacar a una persona de mi grupo de trabajo, siento que podría hacerlo sin mayor dificultad y no me afectaría tanto los sentimientos involucrados. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando debo tomar una decisión, me centro en los hechos sin preocuparme tanto en las emociones involucradas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando debo tomar una decisión, me centro más en mis emociones y en las de los demás, más que en los hechos. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Generalmente los acontecimientos no tienen un impacto emocional tan fuerte en mí. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Generalmente los acontecimientos me impactan emocionalmente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando veo sufrir a alguien, me afecta fuertemente, lo que hace que sienta fácilmente las emociones de los que sufren. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Ver a alguien sufrir, no me afecta mucho emocionalmente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando alguien me cuenta una situación dificil, me involucro emocionalmente con la persona. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando alguien me cuenta una situación difícil, prefiero tomar distancia y no involucrarme tanto emocionalmente con la persona. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'La mayoría de veces, me preocupa mucho cómo se sienten los demás. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'La mayoría de veces, no me preocupa tanto cómo se sienten los demás. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me organizo y planifico lo más que puedo para evitar sorpresas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Organizo y planifico lo mínimo necesario. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Hago listas de chequeo para evitar olvidarme de algo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'A pesar de que pueda olvidarme de algunas cosas, no tiendo a hacer listas de chequeo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando trabajo en grupo, sigo de cerca lo que los demás hacen para cumplir nuestra meta. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando trabajo en grupo, me es difícil seguir de cerca lo que los demás hacen porque estoy en muchas cosas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Creo que las personas me reconocen como una persona más ordenada. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Soy una persona que tiene "su orden" aunque a algunas personas les parezca poco ordenado. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo trabajar de forma espontánea y menos planificada. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo trabajar de forma planificada. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo planificar las actividades sociales y las actividades de mi tiempo libre. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'No suelo planificar ni mi tiempo libre, ni mis actividades sociales. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En mi vida, sigo rutinas programadas porque siento que me ayudan como persona. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Hago las cosas cuando me provocan, las rutinas me encasillan. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Hago las cosas ordenada y sistemáticamente pues sigo un método para ello. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Con frecuencia cambio la forma en que hago las cosas aunque esto me traiga un poco de desorden en algunas oportunidades. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En general, soy meticuloso (cuidadoso) cuando hago mis trabajos aunque me tome más tiempo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En general, me cuesta ser meticuloso (cuidadoso) cuando hago mis trabajos porque priorizo la rapidez. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando sigo rutinas en mi vida, siento que me atrapan y me quitan libertad. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me es fácil seguir rutinas porque me ayudan en la vida. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me gusta tener rutinas, porque me permiten poder tener programadas las actividades que realizo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Las rutinas me molestan, me obligan a tener un horario específico. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Con frecuencia, me es fácil sentir lo mismo que siente la otra persona. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Con frecuencia, me cuesta llegar a sentir lo que la otra persona está sintiendo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'La gente dice que soy de las personas que dice las cosas cuidando mucho el impacto que pueden tener mis palabras. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'La gente dice que soy de las personas que dice las cosas "sin anestesia". (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuido mucho lo que digo porque no quiero que mis comentarios afecten negativamente a otras personas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Soy de las personas que dicen lo que piensa aunque mis comentarios puedan afectar emocionalmente a otros. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando una persona me cuenta un problema de su vida, primero me conecto con sus emociones antes de intentar darle alternativas de solución. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando una persona me cuenta un problema de su vida, primero trato de darle soluciones y luego conectarme con sus emociones. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Las personas que me conocen dicen que por lo general me gusta "darles la contra". (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Las personas que me conocen dicen que soy muy llevadero(a) y que no me gusta mucho "dar la contra". (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando hago un trabajo en grupo, valoro las discusiones aunque eso puede incomodar a algunas personas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando hago un trabajo en grupo, prefiero evitar las discusiones acaloradas para llevar "la fiesta en paz". (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por lo general, digo lo que pienso y llego a contradecir al resto si es necesario. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por lo general, me cuesta decir abiertamente lo que pienso pues trato de mantener la armonía del grupo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'La gente que me conoce dice que tengo mucha imaginación. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'La gente que me conoce dice que soy muy realista y que veo las cosas como son. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por lo general me consideran bueno generando ideas creativas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por lo general me consideran bueno implementando las ideas más que generándolas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Disfruto dejar volar mi imaginación. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento cómodo siendo una persona con los pies bien puestos en la tierra. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Prefiero crear actividades en lugar de mejorar lo que ya existe. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Prefiero mejorar lo que ya existe en lugar de crear actividades. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando llevo un curso que me interesa, disfruto entendiendo la teoría que hay detrás de los conceptos que me están enseñando. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando llevo un curso que me interesa, me cansa la explicación teórica y prefiero que me den los pasos a seguir. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando me compro un equipo nuevo, trato de que funcione sin leer las instrucciones. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando me compro un equipo nuevo, leo las instrucciones antes de usarlo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando me explican un concepto nuevo soy bueno relacionándolo con otros conceptos y experiencias que he aprendido. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Cuando me explican un concepto nuevo soy bueno aplicándolo rápidamente y no invierto mucho tiempo relacionándolo con otros conceptos y experiencias que he aprendido. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En general, mi apariencia (ropa, peinado, etc.) es diferente a la de los demás. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En general, mi apariencia (ropa, peinado, etc.) se parece a la de los demás. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Valoro menos las tradiciones familiares porque siento que me obligan a actuar de una manera determinada. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Valoro las tradiciones familiares porque siento que me dan un sentido de identidad. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En lo personal, disfruto hacer las cosas de manera original, aunque a algunos les parezca que soy un poco extraño(a). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En lo personal, me desagrada que algunos me vean un poco extraño(a), por eso hago las cosas de una manera más convencional. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Me siento cómodo comportándome de manera fuera de lo común (diferente a los demás). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Comportarme fuera de lo común (de manera diferente a lo que hacen los demás) me hace sentir incómodo. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por lo general, las cosas que están a mi alrededor se encuentran ordenadas (ejemplo: mi escritorio). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Por lo general, las cosas que están a mi alrededor no se ven tan ordenadas (ejemplo: mi escritorio). (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Para mí los planes son muy importantes y trato de seguirlos sin cambiarlos tanto. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Para mí los planes son solo una guía por lo que puedo cambiarlos con facilidad. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Soy mejor estructurando y organizando, que adaptándome al cambio. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Soy mejor adaptándome al cambio, que organizando y estructurando. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Mi estilo de vida es más organizado y ordenado, que relajado y libre. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Mi estilo de vida es más relajado y libre, que organizado y ordenado. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo invertir más tiempo para pensar en diferentes alternativas de solución, antes de cerrar e implementar rápidamente. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo cerrar e implementar rápidamente, en lugar de invertir más tiempo en explorar otras alternativas de solución. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo quedarme más tiempo en la lluvia de ideas, antes de pasar a implementar. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'Suelo cerrar e implementar rápidamente, en lugar de quedarme más tiempo en la lluvia de ideas. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En general busco diversas ideas y alternativas de solución, antes de decidir implementar una. (*)'],
            ['carrera_id'=>null,'tipo_encuesta_id'=>3,'nombre'=> 'En general decido e implemento rápidamente, y no invierto mucho tiempo en buscar ideas o alternativas de solución. (*)']
        ];

        Pregunta::insert($temperamentos);
    }
}
