<?php

use App\Rueda;
use Illuminate\Database\Seeder;

class RuedaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rueda = [
            ['nombre' => 'ENMC','descripcion'=>'Personas cálidas, entusiastas y creativas que ven la vida como un lugar con una gran cantidad de posibilidades para hacer o conseguir cosas. Rápida e intuitivamente suelen hacer conexiones entre las diferentes situaciones que viven y suelen actuar en base a las conexiones que hicieron. Tienen una fuerte necesidad de afirmación y aprecio por parte de los otros. Por ello, se interesan mucho por cómo se sienten las otras personas. Asimismo, son claros para expresar sus sentimientos cuando están conversando con alguien. Suelen acompañar a los otros e identificar lo que está sintiendo la otra persona. Sin embargo, debido a su gran energía no son de las personas que se enfocan en escuchar, sino más bien de los que quieren hablar, dar consejos y hacer que la gente se sienta mejor. Estas personas pueden ser espontáneas y flexibles y no se preocupan mucho cuando algo no sale como lo planearon. Para solucionar las dificultades suelen apoyarse en su habilidad para conversar, improvisar y ser creativo.'],
            ['nombre' => 'ENMO','descripcion'=>'Personas cálidas, empáticas y responsables que suelen estar atentas a las emociones, necesidades y deseos de los otros. Ellas, se interesan mucho por los demás e intuyen que todas las personas tienen la posibilidad de crecer e incluso pueden ser los que motivan a que los demás crezcan. Son sociables y en grupo facilitan la comunicación entre los miembros de éste. Suelen ser las personas líderes que ayudan a dirigir los grupos. Son comprometidos con el grupo ya que les interesa la interacción con los demás, pero debido a que también son personas emotivas, les importa cómo se siente el resto de personas. Además, muchas veces se guían de su propia intuición para encontrar soluciones para sus propios proyectos, así como para los compartidos con otras personas. Sus habilidades para organizarse les permiten no sólo orientar sus propias tareas, sino también dirigir a su grupo de amistades o grupo de trabajo.'],
            ['nombre' => 'ENRC','descripcion'=>'Personas ingeniosas y muy alertas que suelen tener facilidad para comunicarse con los demás. Además, utilizan sus propias experiencias y son objetivos para analizar las situaciones alrededor de ellas. Debido a su gran flexibilidad y capacidad para adaptarse ante situaciones inesperadas, cuentan con varias alternativas para solucionar situaciones nuevas y que muchas veces pueden ser bastante retadoras. Son hábiles para generar posibilidades nuevas utilizando los conceptos que conocen para luego analizarlos de manera ordenada y estratégica. Son personas que tienen facilidad para identificar las necesidades de los otros y encuentran que éstas tienen una lógica en común y se pueden ver objetivamente. Además, suelen aburrirse ante la rutina o situaciones repetitivas y prefieren guiarse de lo que su intuición les dice. Están abiertos a las diversas posibilidades, por lo que rara vez enfrentan situaciones de la misma manera y siempre buscan encontrar nuevos temas y nuevas vías para abordar diferentes situaciones.'],
            ['nombre' => 'ENRO','descripcion'=>'Personas sumamente sinceras y directas que por su habilidad expresiva asumen rápidamente el liderazgo. Suelen tener una gran facilidad para identificar errores y por ello pueden rápidamente sugerir alternativas para solucionar las equivocaciones que encontraron. Muchas veces sus propuestas de solución son primordialmente objetivas, pero también se guían de intuición y lo que creen que es lo mejor. Son personas que tienen facilidad para expresar lo que piensan, pero estas ideas son objetivas y cuando hablan, suelen decir las cosas de manera directa. Estas personas se sienten muy cómodas cuando pueden planear, y mejor aún si es posible realizar planes de largo plazo. Por ello, se sienten cómodos planificando y son metódicos al ejecutar el plan que se trazan. Además, presentan sus ideas con gran energía y las exponen como una idea objetiva, sintiendo que posiblemente esa es la verdad sobre ese hecho, por lo que pueden llegar a ser convincentes.'],
            ['nombre' => 'ESMC','descripcion'=>'Personas llevaderas y amigables. Son individuos que aman su modo de vivir intensamente y las relaciones sociales. Esto muchas veces puede llevarlos a ser muy flexibles y no tan disciplinados como podrían ser otras personas. En otras palabras, ven el mundo con mayor tranquilidad y calma que de manera sistemática y organizada. Disfrutan de trabajar en equipo como método para terminar las labores. Tienden a tener una mirada realista hacia el trabajo y suelen intentar hacer que éste sea lo más dinámico posible. Son personas flexibles y espontáneas con gran facilidad para adaptarse a la manera de ser de gente que recién conocen y a nuevos entornos. Además, no se fían tanto de ideas abstractas, sino que necesitan probarlas de tal manera que puedan verificar que éstas son claras y factibles. Finalmente, su lado emotivo les permite ser personas prudentes, comprensivas y preocupadas por quienes tienen alguna preocupación o malestar.'],
            ['nombre' => 'ESMO','descripcion'=>'Personas cálidas y cooperativas que desean que el entorno en el que están sea armonioso y se esfuerzan para conseguir ese tipo de ambientes. Les gusta trabajar en equipo con otras personas con el objetivo de terminar las tareas a tiempo. Siguen sus valores incluso en actividades cotidianas. Están muy atentos a las necesidades de los demás y suelen intentar satisfacer éstas. Estas personas tienen el importante deseo de ser aceptadas por quienes son y lo que pueden dar.  Además, prefieren las actividades que implican interactuar con la gente y se sienten cómodos dando un trato cálido a los demás. Sin embargo, en la interacción con las personas y su manera de ver el mundo, prima la necesidad de trabajar con ideas concretas y que son posibles observar y verificar con la realidad. Asimismo, su carácter emotivo muchas veces puede dificultarles la posibilidad de tomar decisiones sobre los demás y sobre sí mismos, ya que se centran en los sentimientos que hay de por medio a la hora de decidir.'],
            ['nombre' => 'ESRC','descripcion'=>'Personas tolerantes y flexibles que tienen una visión pragmática del mundo y se centran en conseguir resultados inmediatos. No suelen tener mucho interés en las teorías y las explicaciones conceptuales. Suelen ser personas espontáneas que disfrutan pasar el tiempo con gente y le dan gran importancia a lo que ocurre en el presente (“aquí y ahora”). Además, tienen una mayor facilidad para aprender haciendo y no tanto leyendo, ya que necesitan la interacción con otros. Además, se caracterizan por ser personas sumamente realistas. En ese caso, cuando no entienden algo, intentan buscar el sentido lógico y cuál es la premisa que está detrás de la idea. Les cuesta comprender ideas que no tienen una explicación lógica y que es difícil ponerlas en práctica. Por ello, suelen tomar sus decisiones enfocándose en la lógica y en ciertas ocasiones, pueden dejar de lado los aspectos de carácter más emocional'],
            ['nombre' => 'ESRO','descripcion'=>'Personas prácticas y realistas que intentan implementar las decisiones que toman lo más rápido que puedan y no suelen utilizar mucho tiempo para evaluar dichas decisiones. Intentan ser lo más organizadas posible y se enfocan en terminar los proyectos que emprenden lo más pronto y de la manera más eficiente que puedan. Se muestran como personas objetivas e interactúan con los demás utilizando la lógica, porque suelen ver el mundo de una manera práctica y racional. Además, en situaciones emocionalmente intensas,  se mantienen ecuánimes y no se quiebran con facilidad. Esto no significa que no les interesen las emociones de los demás, al contrario, estas personas tienen la intención de interactuar con ellos, pero analizan de manera objetiva cómo se sienten las otras personas. Estas personas tienen una guía propia de cómo se debe realizar una labor, las cuales siguen sistemáticamente y buscan que los demás  hagan lo mismo. Muchas veces sienten la necesidad de implementar sus planes a toda costa a pesar de que pueda existir la posibilidad de incomodar a otras personas en el proceso.'],
            ['nombre' => 'INMC','descripcion'=>'Personas idealistas y seguidoras de sus propios valores y la gente que sienten importante para ellas. Son curiosas y rápidas en encontrar alternativas que pueden ser implementadas en alguna situación. Por ello, suelen ser las personas que motivan a los otros a implementar ideas nuevas. A pesar de ello, también pueden ser personas reservadas, haciendo que su recopilación y análisis de información nueva, no sea comunicada necesariamente. Luego que han logrado concluir la búsqueda de nuevas ideas es que las comparten con los otros (esperan a estar seguros antes de comentar sus ideas).   Muchas veces se guían de su propia inspiración y de su intuición y ésta la emplean tomando en cuenta su interés por las emociones de las personas. Intentan comprender a los otros y apoyarlos ya que tienen gran interés en los sentimientos de los demás. Acostumbran adaptarse a las situaciones y son flexibles a menos que sientan que uno de sus valores está siendo criticado.'],
            ['nombre' => 'INMO','descripcion'=>'Personas que buscan conectar y relacionar ideas para encontrarles un sentido. Este sentido no necesariamente está ligado a lo que es tangible y real. Estas personas pueden encontrar un sentido lógico mediante la utilización de su propia experiencia e instinto y no específicamente utilizando hechos comprobados. Tienen una fuerte curiosidad por entender qué motiva a la gente a hacer cosas y se interesan por los otros. Estas personas suelen desarrollar la habilidad para identificar cuál es la mejor manera de encontrar el bien común entre todo el grupo y se sienten cómodos cuando el grupo está en armonía. Son personas organizadas y muy decididas a implementar su manera de pensar.  Sin embargo, a pesar de su interés por el bienestar de los demás, por momentos pueden ser reservados con sus propios sentimientos. Estas personas suelen escoger a quien compartirle sus sentimientos y pueden ser emotivos en esos momentos.'],
            ['nombre' => 'INRC','descripcion'=>'Personas que buscan encontrarle un sentido lógico a todas las cosas que aprenden. Gustan de los conceptos y lo abstracto y están más interesados en pensar en sus ideas, que en hablar con otras personas. Tienen una gran habilidad para enfocarse en solucionar problemas  que son de su interés. Estas personas suelen ser muy reflexivas y analíticas, por lo que en ciertas situaciones pueden ser muy críticas y con dificultad para aceptar rápidamente ideas con una baja explicación lógica. Además, no tienden a ser muy comunicativas, sino más reservadas y críticas cuando es necesario hacerlo. Lo más frecuente que ocurre con ellas, es que analizan en silencio las situaciones de manera lógica y piensan en varias alternativas de solución, las mismas que se les ocurren utilizando sus experiencias pasadas. En ese caso también pueden ser personas flexibles que ante dificultades utilizan la lógica para adaptarse y encontrar soluciones.'],
            ['nombre' => 'INRO','descripcion'=>'Personas que suelen ser muy creativas, y tienen un gran deseo de implementar ideas nuevas para conseguir sus metas. Ellas pueden encontrar patrones comunes en las situaciones del ambiente y suelen desarrollar explicaciones del por qué se han dado las diferentes situaciones. Si bien suelen adquirir sus ideas utilizando su intuición, son personas lógicas y objetivas. En ese caso, es importante que las ideas que encontraron mediante su experiencia sean lógicas, racionales y muchas veces que las puedan ver como objetivas.  Cuando se comprometen con alguna tarea, suelen organizarse para terminar la labor que tienen pendiente. En este caso, utilizan la planificación y la suelen ejecutar de manera ordenada y metódica. Son personas que suelen cuestionar las situaciones en búsqueda de la razón y lo que consideran que puede ser la verdad objetiva. Estas personas son independientes y pueden ser muy exigentes no sólo con ellos mismos, sino también con los demás. Sin embargo, su cuestionamiento y búsqueda de la razón lógica no necesariamente es abierta, ya que son personas que son más reservadas y piensan primero sus ideas antes de realizar algún tipo de cuestionamiento.'],
            ['nombre' => 'ISMC','descripcion'=>'Personas calladas, amigables y sensibles que valoran mucho el presente y lo que está pasando alrededor de ellas. Gustan de tener sus propios horarios y poder trabajar manejando sus tiempos. En ese caso, son sumamente comprometidos con los trabajos que realmente les importa, siempre y cuando les den la posibilidad de realizarlo en sus propios tiempos. No suelen agradarles los desacuerdos y evitan el conflicto a todo costo, por lo que frente a un desacuerdo pueden preferir respetar la opinión del otro a pesar de que ésta no sea del todo consecuente con sus principios. Son leales y suelen recordar características específicas de las personas que son significativas para ellas. Se preocupan por los sentimientos de los demás y tratan de generar ambientes armoniosos en la casa y en el trabajo. En general, pueden ser vistos como personas emotivas, con la habilidad para acompañar emocionalmente a otros, ya que comprenden muy bien cómo se sienten los demás.'],
            ['nombre' => 'ISMO','descripcion'=>'Personas calladas, responsables y que hacen las actividades con mucho cuidado y atención. Son perseverantes, cuidadosas y enfocadas en sus obligaciones. Son leales y suelen recordar características específicas de las personas que son significativas para ellas. Se preocupan por los sentimientos de los demás y tratan de generar ambientes armoniosos en la casa y en el trabajo. En general, pueden ser vistos como personas emotivas, con la habilidad para acompañar emocionalmente a otros, ya que se identifican con los sentimientos de ellos. Sin embargo, estas personas acostumbran acompañar a los demás pero no interactúan tanto con ellos. En ese caso, prefieren escuchar y filtrar la información a través de lo que ven y escuchan. Asimismo, al realizar una evaluación de la información, comprenden lo que le va ocurriendo al otro. Son personas que se les puede ver como amables, comprensivas y diplomáticas.'],
            ['nombre' => 'ISRC','descripcion'=>'Personas tolerantes y flexibles, suelen ser calladas y observadoras, hasta que una dificultad aparece. Ante esta situación acostumbran actuar de manera calmada hasta que solucionan el problema. Habitualmente analizan las situaciones que funcionan, manejan una gran cantidad de información y prefieren enfocarse en situaciones más conceptuales que prácticas. Estas personas creen que la información se obtiene mediante la causa y el efecto utilizando la lógica para conocer los hechos. Valoran la eficiencia y la entienden como la ejecución de tareas de manera sumamente metódica y organizada. Utilizan reglas y la deducción para llegar a crear ideas y argumentos y se sienten buenos empleando este método. Asimismo, tienen dificultad para aceptar y comprender explicaciones que carecen de un sentido lógico. Por ello, en ciertas ocasiones pueden dejar de lado los aspectos de carácter más emocional para tomar una decisión. Esto podría llevarlos a no sentirse tan afectados con las emociones ajenas. Valoran la eficiencia y la entienden como la ejecución de tareas de manera sumamente organizada.'],
            ['nombre' => 'ISRO','descripcion'=>'Personas calladas, detallistas y minuciosas, lo que puede permitirles ser cuidadosas a la hora de trabajar, siempre tomando en cuenta los detalles y la prolijidad de los mismos. Son personas organizadas en diferentes aspectos de sus vidas y ello les permite tener recursos variados para enfrentar las tareas que se les presenten. Además, son sumamente trabajadoras y cuidadosas con los procedimientos y el orden de cómo hacer las cosas. Eligen los temas de conversación en los que desean participar y no suelen interactuar mucho en conversaciones banales con gente que recién conocen. Estas personas acostumbran mostrarse calmadas y ecuánimes la mayor parte del tiempo. Al ser personas realistas y prácticas, suelen decidir utilizando la lógica, y ello hace que intenten expresar lo que dicen de manera clara. Cuando trabajan, se orientan a conseguir la meta que se proponen y a encontrar información que sea objetiva o que pueda ser catalogada como verdadera. En sí, su búsqueda de la verdad podría hacer que incurran en debates ya que le dan suma importancia a la información objetiva. Se sienten cómodos de tener los diversos aspectos de su vida ordenados y organizados.'],
        ];

        Rueda::insert($rueda);
    }
}
