INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS','Fiorella Ginocchio','313-3333','123@upc.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ANA ARRIETA','Ana ARRIETA','6529844','ANACE1603@DAVIDFISCHMAN.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('DANIEL OSES RUIZ PRUEBA','Daniel Osés Ruiz','4444675','daniel.oses@upc.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VILLA CARITAS','colegio villa caritas','31333333','javier@hotmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('CEGNE CLARETIANO','Verónica Palacios Boza','4510353','vpalacios@claretiano.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CASUARINAS','Cecilia Calvimontes','3444040','ccalvimontes@casuarinas.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LEON PINELO','Carlos Solórzano','2183040','carlos@lp.com.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NEWTON','KARLA BRAVO','2079990','karla.bravo@newton.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO WEBERBAUER','Liliana Diaz','436 6212','ldiaz@weberbauer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA MARIANISTAS','JOAQUIN COK','3721831','JCOK@SANTAMARIA.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN SILVESTRE','San Silvestre','2413334','colegio@sansilvestre.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ABRAHAM LINCOLN','Abraham Lincoln','6174500','colegio@abrahamlincoln.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JEAN LE BOULCH','Jean Le Boulch','3480844','informes@leboulch.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ALEXANDER VON HUMBOLDT','Re Villanueva','6179090','rvillanueva@humboldt.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PEDRO RUIZ GALLO','Pedro Ruiz Gallo','6514056','iepprg@prg-chorrillos.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NSRA RECONCILIACION','Nuestra Sra de la Reconciliación','437-3307','secretaria@colegionsr.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO EL CARMELO','El Carmelo','5330029','cepelcarmelo@elcarmelolima.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CLEMENTE ALTHAUS','Clmente Althaus','419-4700','matricula@clementealthaus.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LOS ALAMOS','Los Alamos','4631044','colegio@losalamos.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE DE CLUNY','San Jose de Cluny','221-2890','clunybco@hotmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN CHARBEL','SAN CHARBEL','4608311','informes@colegiosancharbel.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SRA DE LA PAZ','NUESTRA SEÑORA DE LA PAZ','2631029','colegio_nsp_fmnj@hotmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PESTALOZZI','PESTALOZZI','617 8600','colsuizo@pestalozzi.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('LICEO NAVAL CONTRALMIRANTE MONTERO','NAVAL CONTRALMIRANTE MONTERO','6137600','exalumnos_montero@hotmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO REINA DE LA PAZ','REINA DE LA PAZ','637-5617','informes@ssccreinadelapaz.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JUAN MARIA VIANNEY','San Juan María Vianney','6524420','consulta@virrey.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO','SAN ANTONIO','429-2524','webmaster@csa.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NIÑO JESUS DE PRAGA','NIÑO JESUS DE PRAGA','484-1377','secretaria@praga.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ISAAC NEWTON VENTANILLA','ISAAC NEWTON VENTANILLA','5534998','informes@cin.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ANA','SANTA ANA','263-3726','colegio_lima@staana.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PERUANO JAPONES LV','PERUANO JAPONES','6376619','colegioperuanojapones@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA REINA MARIANITAS','MARIA REINA MARIANITAS','2011010','colegio@mariareinamarianistas.net','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DE JESUS','JESUS','463-0156','secretaria@colegiodejesusperu.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SRA DE LA REPARACION','SEÑORA DE LA REPARACION','4452297','lareparacion@lareparacion.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO REINA DEL MUNDO','REINA DEL MUNDO','4792191','reina-schule@rdm.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JESUS ES MI LUZ','JESUS ES MI LUZ','498-7654','jml.colegio@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SRA DEL CONSUELO','SRA DEL CONSUELO','208 - 8628','colegio@nsconsuelo.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO WALT WITMAN','WALT WITMAN','5285208','waltwhitmanschool@outlook.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DIAS FELICES','DIAS FELICES','4641866','contacta@diasfelices.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ROQUE','SAN ROQUE','274-2955','informes@sanroque.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARTIN ADAN','MARTIN ADAN','5231625','informes@martinadan.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ESCUELA DE TALENTOS','ESCUELA DE TALENTOS','574 9873','escueladetalentosgrc@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA LINCE','SANTA ROSA','4700912','direccion@santarosadelima.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ST. GEORGES','ST GEORGES','4458147','informes@stgeorgescollege.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS','SACO OLIVEROS','717-2720','contactanos@sacooliveros.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO BELEN','BELEN','4402235','informes@ssccbelen.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA MARIA','SANTISIMA MARIA','713 1339','nformes@santisimamaria.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ELIM','ELIM','4314034','informes@colegioelim.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO MARIANITAS','SAN ANTONIO MARIANITAS','4293712','csam@sanantonio.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LNGA','Liceo Naval Germán Astete','420-6455','lnastete@Lnga.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('PARTNERSHIP','PARTNERSHIP','5366399','informe@partnership.com.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PIO XII','PIO XII','4361001','informes@pio.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO POLO JIMENEZ','POLO JIMENEZ','959 662 910','informes@polojimenez.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ISABEL DE HUNGRÍA','SANTA ISABEL DE HUNGRÍA','4255152','info@santaisabelhungri.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VILLA MARIA','VILLA MARIA','3681634','consulta@vmaria.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO WEBERBAUER','WEBERBAUER','436-6212','informes@weberbauer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO HIRAM BINGHAM','HIRAM BINGHAM','2719880','conctaco@hirambingham.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO FERMIN TANGUIS','FERMIN TANGUIS','4594591','ecb_3007@hotmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA DE LA PROVIDENCIA','MARIA DE LA PROVIDENCIA','4853295','mariaprovidencia@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTIAGO APOSTOL','SANTIAGO APOSTOL','5695825','santiagoapostol@edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN NORBERTO','NORBERTO','4729447','informes.cpsn@sannorberto.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA RITA DE CASIA','SANTA RITA DE CASIA','404627','adminitracion@santarita.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VILLA MARIA LA PLANICIE','VILLA MARIA','445-3592','villamaria@vmm.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA ESPERANZA','NUESTRA SEÑORA DE LA ESPERANZA','4345870','usuario@nse.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN CLEMENTE','CLEMENTE','261-4205','informes@sanclemente.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ALTAIR','ALTAIR','365-0298','secretaria@altair.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ROOSEVELT','ROOSEVELT','511-435-089','admissions@amersol.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('LAUREATE INTERNATIONAL','LAUREATE','5366399','LAUREATE@GMAIL.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LIMA VILLA','LIMA','2553232','contactenos@limavillacollege.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CAMBRIDGE','CAMBRIDGE','2540107','office@cambridge.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN PEDRO - SANTISIMA TRINIDAD','SAN PEDRO','5366399','informes@colegiosanpedro.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE BARRANCO','ROSA','477-3330','informes@colegiosantarosafmm.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('upc2017','HUMBERTO','5366399','asdasdasd@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTISIMO NOMBRE DE JESUS','JESUS','53663399','snj@santisimo.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA INMACULADA','INMACULADA','5966933','soporte@inmaculada.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SALCANTAY','SANCALTAY','4359223','Informes@salcantay.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO AGUSTINIANO','AGUSTINIANO','4272368','agustinianosanmartindeporres@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE DE MONTERRICO','SAN JOSE','3442203','sanjosemonterrico@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTO REY','CRISTO','261 6721','crey@cristorey.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DIVINO MAESTRO','MAESTRO','2542858','iedivinomaestro@gmail.com','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA ALVARADO','ALVARADO','931 475 484','postmast@cma.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTO DOMINGO APOSTOL','APOSTOL','6071108','informes@sda.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LIZARDO MONTERO','LIZARDO','5366399','informes@lizardo.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JOHANNES GUTENBERG','JOHANNES','3270781','info@johannesgutenberg.org','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAINT PATRICK','PATRICK','5366399','informe@spc.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SALESIANO','SALESIANO','5366399','informes@salesiano.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO REINA DE LAS AMERICAS','JAVIER','99999999','JAVIER@UPC.EDU.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA MERCED','GABRIELA','9888888','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MONTEALTO','GABRIELA','9876543','MONTEALTO@UU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VILLA ALARIFE','GABRIELA','977777778','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CLARETIANO','GABRIELA','999999995','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ABRAHAM VALDELOMAR','GABRIELA','979797977','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO EMILIO SOYER CABERO','GABRIELA','951169228','GABRIELA@UU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIOS','GABRIELA','981107229','GABRIELA@UU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MATEMÁTICO SANTÍSIMA MARÍA','GABRIELA','95694623','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JESUS SALVADOR','GABRIELA','956932117','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VILLA CARITASS','GABRIELA','910264557','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL PILAR','GABRIELA','912205443','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE LIMA','GABRIELA','974825116','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN FELIPE','GABRIELA','985526440','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA SALLE','GABRIELA','969626559','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CARMELITAS','GABRIELA','901222663','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ESPECIALES','GABRIELA','950032116','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MIXTO SANTA TERESITA','GABRIELA','950026339','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MÓNICA','GABRIELA','921102336','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LEONARD EULER','GABRIELA','940013229','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN PABLO','GABRIELA','912345678','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA URSULA','GABRIELA','912356779','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE Y REDENTOR','GABRIELA','973456723','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PRESCOTT','GABRIELA','985643279','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO INTERNACIONAL','GABRIELA','934521468','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ANGELA','GABRIELA','912837567','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE SAN ISIDRO','GABRIELA','912289345','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA REPARACION','GABRIELA','943578925','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JESUS REPARADOR','GABRIELA','912845670','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MI HOGAR Y ESCUELA','GABRIELA','912908678','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SALCANTAY','GABRIELA','978896445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA RECOLETA','GABRIELA','912300998','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA AUXILIADORA','GABRIELA','934527892','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LICEO MONTERO','GABRIELA','956789556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTO REDENTOR','GABRIELA','915698776','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ISABEL DE HUNGRIA','GABRIELA','916789556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ANDRES','GABRIELA','934578900','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MAX UHLE','GABRIELA','912345670','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO COOPERATIVO SAN FELIPE','GABRIELA','908845882','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTO TOMAS DE AQUINO','GABRIELA','987767556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SRA DE LA CONSOLACION','GABRIELA','912356778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARCELINO CHAMPAGNAT','GABRIELA','987767889','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL ROSARIO','GABRIELA','998978990','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ANNIES SCHOOL','GABRIELA','998878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SEÑOR DE LA MISERICORDIA','GABRIELA','998876783','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SCM','GABRIELA','923345223','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO INGLES DE MUJERES MATER ADMIRABILIS','GABRIELA','994466778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ALBERTO BENJAMIN SIMPSONS','GABRIELA','987767551','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO FAP QUIÑONES','GABRIELA','906678556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LORD BYRON','GABRIELA','984467889','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARKHAM COLLEGE','GABRIELA','956645667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PERUANO ALEMAN BEATA IMELDA','GABRIELA','987767556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN LUIS','GABRIELA','989978991','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CORAZÓN DE MARÍA','GABRIELA','987767883','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO IEA MIRAFLORES','GABRIELA','986688994','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ENRIQUE MEIGGS','GABRIELA','989907664','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO','GABRIELA','989900446','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO WINNETKA','GABRIELA','987765661','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DOMINGO SAVIA','GABRIELA','9099090098','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO BRITANICO EUROPEO DUNALASTAIR','GABRIELA','989909541','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO BARTOLOME HERRERA','GABRIELA','989989775','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA DE LA GRACIA','GABRIELA','908854334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA','GABRIELA','983345221','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE DE CHACLACAYO','GABRIELA','909988123','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LICEO NAVAL JUAN FANNING GARCIA','GABRIELA','907767441','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE','GABRIELA','908855443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO EL CARMELO','GABRIELA','908899667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN GABRIEL','GABRIELA','9988556678','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO UNIVERSO CHORRILLOS','GABRIELA','9988786612','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA INES','GABRIELA','908876552','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO INKA GAKUEN','GABRIELA','909988774','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NIVEL A','GABRIELA','989900778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PARTICULAR CORAZON DE JESUS PIONERO','GABRIELA','908878778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CORAZON DE JESUS PIONERO DE LA CIENCIA','GABRIELA','908877881','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JOSEPH AND MERY HIGH SCHOOL','GABRIELA','988878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PERUANO CHINO JUAN 23','GABRIELA','989909886','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ITALIANO ANTONIO RAIMUNDI','GABRIELA','989934556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO AURELIO MIROQUESADA','GABRIELA','989967554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SKINNER','GABRIELA','989912331','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN AGUSTIN','GABRIELA','904455664','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO YACHAYHUASI','GABRIELA','9088786678','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA TERESITA','GABRIELA','987755443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('INSTITUCION PARTICULAR DE LA CRUZ','GABRIELA','985543445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA ASUNCIÓN','GABRIELA','9877898887','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MONTERRICO CHRISTIAN SCHOOL','GABRIELA','984434552','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO IEP SANTA ANITA','GABRIELA','989967441','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO HECTOR DE CARDENAS','GABRIELA','984412334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO RAYMOND CLARK','GABRIELA','986656445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACRADO CORAZON DE BELEN','GABRIELA','908877661','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO BRUNING','GABRIELA','907734556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LE D\'ALEMBERT','GABRIELA','987765442','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN PEDRO','GABRIELA','980078556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO HANS CHRISTIAN ANDERSON','GABRIELA','9899098889','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO IEP ADVENTISTA MIRAFLORES','GABRIELA','987756443','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LIBERTADOR SAN MARTIN','GABRIELA','908866775','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ROBERT LETOURNEAU','GABRIELA','987767556','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN MARCOS DE MONTERRICO','GABRIELA','9899900876','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JUAN ENRIQUE NEWMAN','GABRIELA','987767556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUEVO MUNDO','GABRIELA','988878665','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VIRGEN DE LA ASUNCION','GABRIELA','987756442','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO HORACIO PATIÑO','GABRIELA','98675643','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ENRIQUE CAMINO BRENT','GABRIELA','983356778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DAVID AUSEBEL','GABRIELA','983423112','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN RAFAEL','GABRIELA','986756443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MELVIN JHONS SAN LUIS','GABRIELA','986656445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CHARBEL','GABRIELA','987767543','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PERPETUO SOCORRO DE TRUJILLO','GABRIELA','986756666','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PERUANO CHINO DIEZ DE OCTUBRE','GABRIELA','985645667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('EVENTO SAN ISIDRO','GABRIELA','987767554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DIVINO REDENTOR','GABRIELA','986755434','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CHRISTIAN SCHOOL','GABRIELA','988878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PARROQUIAL SAN JASE','GABRIELA','98889789887','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARTER PURISIMA','GABRIELA','985645334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MATILE','GABRIELA','0978856785','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ANDREAX','GABRIELA','09211692','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN IGNACIO DE LOYOLA','GABRIELA','908856443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS ARANCIBIA','GABRIELA','987767556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAINT GEORGES','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COEGIO MARIA E LAS MERCEDES','GABRIELA','908867553','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA DE LAS MERCEDES','GABRIELA','907756443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA MOLINARI','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ALGARROBOS-CHICLAYO','GABRIELA','907789667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN AGUSTIN CHICLAYO','GABRIELA','907789008','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ALTERNATIVOS TALENTOS TRU','GABRIELA','908878556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CLARETIANO TRU','GABRIELA','908834223','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE OBRERO TRU','GABRIELA','98667856','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA INMACULADA TRU','GABRIELA','986678445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DE CIENCIAS LORD KELVIN TRU','GABRIELA','9345665544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SIR ALEXANDER FLEMING TRU','GABRIELA','897767554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO DE PADUO','GABRIELA','988878665','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MONTEALTO','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MANUEL PARDO CHICL','GABRIELA','908878556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTO TORIBIO DE MOGROVEJO CHICL','GABRIELA','985567445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CEIBOS','GABRIELA','903423441','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PARROQUIAL SANTA ROSA DE LIMA','GABRIELA','9866756445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NOE','GABRIELA','984456778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LORD KELVIN TRUJILLO','GABRIELA','988878556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTO TORIBIO DE MOGROVEJO TRU','GABRIELA','912234556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TALENTOS TRU','GABRIELA','985644556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VIRGEN DE FATIMA DE BARRANCO','GABRIELA','908867554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PITAGORAS','GABRIELA','967855220','GABRIELA@U.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SEÑOR DE LUREN','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MAGISTER','GABRIELA','946566776','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN IGNACIO DE LOYOLA PIU','GABRIELA','907767554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA MONTESSORI PIU','GABRIELA','908845334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TURICARA PIU','GABRIELA','907767556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VALLESOL PIU','GABRIELA','904455667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA PIU','GABRIELA','902234445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO INMACULADO HIGH SCHOOL','GABRIELA','986678556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO BADEM POWELL','GABRIELA','908897778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO EL PINAR HUARAZ','GABRIELA','934456778','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JEAN PIAGET','GABRIELA','986675445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO FAP FRANCISCO SECADA VIGNETTA','GABRIELA','988878552','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('CLEGIO HEMINGWAY','GABRIELA','9077342567','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO EL BUEN PASTOR','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACOS OLIVEROS INGENIEROS','GABRIELA','907789665','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ACUARELA-CAJAMARCA','GABRIELA','9088907898','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTO SALVADOR','GABRIELA','98776755','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('EVENTOS MONTERRICO','GABRIELA','984456334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SOPHIANUM','GABRIELA','987767554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO FRANCO PERUANO','GABRIELA','98767887','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN VICENTE DE PAUL','GABRIELA','985523225','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL BUEN CONSEJO','GABRIELA','945567443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VIRGEN DE LA INMACULADA','GABRIELA','987767443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN MARTIN DE PORRAS-SANTA ANITA','GABRIELA','98445678','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO COMAS EL RETABLO','GABRIELA','986656445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCA SI','GABRIELA','996678775','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCA MO','GABRIELA','985565667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCA SM','GABRIELA','942212334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCA VI','GABRIELA','983344556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO MARISTA','GABRIELA','9844345567','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA MERCED SUR','GABRIELA','9855677775','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS LURIN','GABRIELA','98445665533','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO  Institucion Educativa Particular De La Cruz','GABRIELA','9844567754','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ENRIQUE NAPOLEON','GABRIELA','98433222344','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA TERECITAAA','GABRIELA','98575644355','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS PUENTE PIEDRA','GABRIELA','984456788','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS VENTANILLA','GABRIELA','98655445','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CEGNE ANDARES','GABRIELA','986785443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN FRANCISCO DE SALES','GABRIELA','98765456434','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA MARIA DE LOS CEDROS','GABRIELA','90887744566','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS LA VICTORIA','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRENTO COLONIAL','GABRIELA','908878667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO SALAVERRY','GABRIELA','9867878','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ISSAC NEWTON','GABRIELA','987766765565','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO HOSANNA','GABRIELA','986756556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO BERKELEY SCHOOL','GABRIELA','987767666','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SOR ANA DE LOS ANGELES','GABRIELA','9876765','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ASOCIACION EDUCATIVA HOGAR Y ESCUELA','GABRIELA','98566332','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CEGNE SANTA ANITA','GABRIELA','9811232111','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PUNTA ARENAS','GABRIELA','98565433333','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA EUFRASIA','GABRIELA','9086456633','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO CIPRECES','GABRIELA','908867554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA FE DE MARIA','GABRIELA','9877809987','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SEBASTIAN SALAZAR BONDY','GABRIELA','987787654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO NARANJAL','GABRIELA','98008976','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA GORETI','GABRIELA','90887544433','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TORIBIO LUZURIAGA','GABRIELA','94565679098','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MATER CHRISTI','GABRIELA','98564455433','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL CARMEN','GABRIELA','98532345','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JUAN BAUTISTA LA SALLE','GABRIELA','985568766','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA MERCED SEDE CENTRAL','GABRIELA','986556545','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS MONTESORI','GABRIELA','9855544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PASCUAL SACO OLIVEROS','GABRIELA','987665444','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA RECONCILIACIÓN','GABRIELA','987765555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TECNIMEDIA CEPEBAN','GABRIELA','9878796654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PARROQUIAL MARIA DE LA PROVIDENCIA','GABRIELA','987766775','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CLARA COGORNO DE COGORNO','GABRIELA','986564543','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JUAN DE BARRANCO','GABRIELA','98332321','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO AMERICA','GABRIELA','987767656','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MIGUEL ANGEL BUONARROTI','GABRIELA','9877677668','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACRADOS CORAZONES','GABRIELA','9887878899','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA VIRGEN DE LA PUERTA','GABRIELA','989977654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CORPORACION EDUCTIVA  CORAZON DE JESUS','GABRIELA','988877666','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA PARADO DE BELLIDO','GABRIELA','9077665544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MANUEL POLO JIMENEZ','GABRIELA','98554543','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTO VICTORIOSO','GABRIELA','986767655','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ATENEO DE LA MOLINA','GABRIELA','98665654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JESUALDO','GABRIELA','98786553','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS VILLA EL SALVADOR','GABRIELA','986655544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO HIPOLITO UNANUE','GABRIELA','98553333','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ADAM SMITH','GABRIELA','94353222','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA CASA DE CARTON','GABRIELA','93544333','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA REICHE','GABRIELA','9854543333','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO STEPHEN HAWKING','GABRIELA','9821124555555555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ROSA DE SANTA MARIA','GABRIELA','953322344','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LOS PEREGRINOS','GABRIELA','90556753','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO GRUPO B','GABRIELA','94545336','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA TRINIDAD','GABRIELA','932324565','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PARTICULAR DE JESUS','GABRIELA','98643221134','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CESAR VALLEJO','GABRIELA','98443432','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA UNION','GABRIELA','964434223','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ANGELES DE LA PAZ','GABRIELA','954543442','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SALESIANO SANTA ROSA','GABRIELA','914435251','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MONTESSORI','GABRIELA','98554322','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('Colegio GAF','Humberto','993538598','hgutierrezGAF@gaf.com.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTO REY TACNA','GABRIELA','982232344','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA INMACULADA CALIFORNIA','GABRIELA','953422666','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL PERPETUO SOCORRO','GABRIELA','98655433','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS ATE','GABRIELA','9743466654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS PRO','GABRIELA','9645332','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LA MOLINA CHRISTIAN','GABRIELA','98353534','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACRADO CORAZON DE LA MOLINA','GABRIELA','97543222','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO AMERICA DEL CALLAO','GABRIELA','975432333','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LICEO NAVAL GERMAN ASTETE','GABRIELA','9765544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACRADO CORAZON','GABRIELA','987655555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA MERCED ATE','GABRIELA','976666544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE CHOSICA','GABRIELA','98655433','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JOSEPH AND MERY HIGH SCHOOL','GABRIELA','987654433','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MI JESUS','GABRIELA','965545433','GABRIELA131RR@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ALBERT EINSTEIN','GABRIELA','954564344','GABRIELAIII@UU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO LOS LIERTADORES','GABRIELA','986544554','GABRIELAOOO@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PITAGORAS NUEVO SAN JUAN','GABRIELA','987654676','GABRIELATTT@UU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CARLOS LISSON','GABRIELA','98655544','GABRIELS9@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO REINA DE LOS ANGELES','GABRIELA','975656633','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JESUS Y REDENTOR','GABRIELA','9754644344','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ANGELA MERICI','GABRIELA','987665545','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL CALVO','GABRIELA','987676555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL BRITTO','GABRIELA','9875466644','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL TOCHE','GABRIELA','9886886876','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL CAMACHO','GABRIELA','9877766765','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL COPPOLA','GABRIELA','988787688','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL VIZCARDO','GABRIELA','9876656675','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DIVINA TRINIDAD','GABRIELA','965665444','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO IRMA DOLORES','GABRIELA','98655454','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTINA ANNIE SOPPER-MOYOBAMBA','GABRIELA','98676544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA DE NAZARET-CAJAMARCA','GABRIELA','97867566655','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN JUAN BAUTISTA-PUNO','GABRIELA','98867555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SIMON BOLIVAR -TARAPOTO','GABRIELA','978676555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRENTO ESCARDO','GABRIELA','98777766','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL CONSUELO -SAN MIGUEL','GABRIELA','98878676','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE FATIMA','GABRIELA','988767656','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SOR ANA DE LOS ANGELES SJL','GABRIELA','988786765','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ANDRES BELLOS','GABRIELA','988777667','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CRISTIANO PIONERO','GABRIELA','988777655','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO INTERNACIONAL DE LIMA SURCO','GABRIELA','988776554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE LIMA SAN BORJA','GABRIELA','98877666','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JUAN INGUNZA VALDIVIA','GABRIELA','98877676','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA DE ICA','GABRIELA','9887890988','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTA ANA SAN MIGUEL','GABRIELA','98878767','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PIEDRA HERRERA LUCERO DEL CARMEN','GABRIELA','9787876555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO JUAN LINARES ROJAS','GABRIELA','98877766','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CIENCIAS DE TARAPOTO','GABRIELA','97867654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO ANDRE MALRAUX','GABRIELA','988787776','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO DE HUAMANGA -AYACUCHO','GABRIELA','9887888','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTO DOMINGO EL PREDICADOR','GABRIELA','9880009998','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VILLA JARDIN','GABRIELA','988775555','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA CRUZ','GABRIELA','9776776766','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DIVINA PROVIDENCIA','GABRIELA','98867655','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS SEDE SORIA','GABRIELA','988767656','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MONSENOR MARCOS LIBARDONI','GABRIELA','98786876','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO CEP UNI','GABRIELA','9765545544','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN RICARDO','GABRIELA','956343244','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('UNIVERSIDAD ANDRES BELLO CHILE','GABRIELA','97861243432','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DALTON','GABRIELA','956443322','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRENER','GABRIELA','97756565654','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PALESTRA','GABRIELA','905545324','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SEBASTIAN SALAZAR BONDI -SANTA ANITA','GABRIELA','906656444','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PERUANO CHINO CHICLAY','GABRIELA','983443455','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO GEORGE COLLEGE','GABRIELA','963355334','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO VICTORIA BARCIA','GABRIELA','9855334322','GABRIELA@UUUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO MARIA AUXILIADORA- CALLAO','GABRIELA','974332222','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO SAN FRANCISCO - SAN BORJA','GABRIELA','92323344','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO DOMINGO FAUSTINO SARM-PUENTE PIEDRA','GABRIELA','9544242443','GABRIELA@UUU.COM.PE','1');

INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE SANTA ANITA','TRILCE','354-2207','atencionalcliente@trilce.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE LA MOLINA','TRILCE LA MOLINA','437-6540','trilcelm@colegio.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE VILLA EL SALVADOR','VES','619-8105','atencionalcliente@trilce.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE CHORRILLOS','TRILCE','619-8104','atencionalcliente@trilce.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE SALAVERRY','GABRIELA','924596299','GABRIELA@UU.PE.COM','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE SAN ISIDRO','GABRIELA','988867553','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE TRU','GABRIELA','923456334','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRILCE CHICLAYO','GABRIELA','964434556','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO TRENTO TRILCE','GABRIELA','987655444','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER PUENTE PIEDRA','PAMER','719-2959','admision@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER JESUS MARIA','PAMER JESUS MARIA','7197349','adminision@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER VILLA EL SALVADOR','PAMER','719-3732','admision@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER IZAGUIRRE','IZAGUIRRE','7197777','admision@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER SAN ISIDRO','ISIDRO','7197360','pamer@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER CARABAYLLO','PAMER','5366399','informes@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('Colegio Pamer Contisuyo','conti','993538599','conti@pamer.edu.pe','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER LINCE','GABRIELA','945678990','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER CAJAHUAMAN','GABRIELA','980090007','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER CHORRILLOS','GABRIELA','987756443','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER MAGDALENA','GABRIELA','908878664','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER','GABRIELA','9644420225','GABRIELA@U.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER COMAS','GABRIELA','908878990','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER LAS ARENAS -PIURA','GABRIELA','98878884','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER REPUBLICA DE CHILE','GABRIELA','986656543','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER BARRANCO','GABRIELA','987767666','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER LA LIBERTAD','GABRIELA','908876554','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER DURAZNOS','GABRIELA','9844568776','GABRIELA@UUU.COM.PE','1');
INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO PAMER SALAMANCA','GABRIELA','986665444','GABRIELA@UUU.COM.PE','1');

INSERT INTO `empresas` (`razon_social`,`contacto`,`telefono`,`email`,`insert_user_id`) VALUES ('COLEGIO INNOVA CORPORACIÓN','','','','1');





