INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS',3,'1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ANA ARRIETA','4','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('DANIEL OSES RUIZ PRUEBA','5','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VILLA CARITAS','6','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('CEGNE CLARETIANO','7','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CASUARINAS','8','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LEON PINELO','9','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NEWTON','10','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO WEBERBAUER','11','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA MARIANISTAS','12','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN SILVESTRE','13','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ABRAHAM LINCOLN','14','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JEAN LE BOULCH','15','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ALEXANDER VON HUMBOLDT','16','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PEDRO RUIZ GALLO','17','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NSRA RECONCILIACION','18','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO EL CARMELO','19','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CLEMENTE ALTHAUS','20','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LOS ALAMOS','21','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE DE CLUNY','22','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN CHARBEL','23','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SRA DE LA PAZ','24','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PESTALOZZI','25','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('LICEO NAVAL CONTRALMIRANTE MONTERO','26','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO REINA DE LA PAZ','27','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JUAN MARIA VIANNEY','28','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO','29','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NIÑO JESUS DE PRAGA','30','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ISAAC NEWTON VENTANILLA','31','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ANA','32','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PERUANO JAPONES LV','33','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA REINA MARIANITAS','34','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DE JESUS','35','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SRA DE LA REPARACION','36','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO REINA DEL MUNDO','37','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JESUS ES MI LUZ','38','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SRA DEL CONSUELO','39','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO WALT WITMAN','40','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DIAS FELICES','41','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ROQUE','42','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARTIN ADAN','43','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ESCUELA DE TALENTOS','44','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA LINCE','45','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ST. GEORGES','46','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS','47','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO BELEN','48','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA MARIA','49','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ELIM','50','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO MARIANITAS','51','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LNGA','52','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('PARTNERSHIP','53','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PIO XII','54','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO POLO JIMENEZ','55','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ISABEL DE HUNGRÍA','56','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VILLA MARIA','57','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO WEBERBAUER','58','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO HIRAM BINGHAM','59','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO FERMIN TANGUIS','60','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA DE LA PROVIDENCIA','61','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTIAGO APOSTOL','62','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN NORBERTO','63','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA RITA DE CASIA','64','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VILLA MARIA LA PLANICIE','65','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA ESPERANZA','66','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN CLEMENTE','67','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ALTAIR','68','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ROOSEVELT','69','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('LAUREATE INTERNATIONAL','70','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LIMA VILLA','71','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CAMBRIDGE','72','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN PEDRO - SANTISIMA TRINIDAD','73','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE BARRANCO','74','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('upc2017','75','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTISIMO NOMBRE DE JESUS','76','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA INMACULADA','77','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SALCANTAY','78','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO AGUSTINIANO','79','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE DE MONTERRICO','80','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTO REY','81','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DIVINO MAESTRO','82','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA ALVARADO','83','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTO DOMINGO APOSTOL','84','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LIZARDO MONTERO','85','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JOHANNES GUTENBERG','86','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAINT PATRICK','87','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SALESIANO','88','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO REINA DE LAS AMERICAS','89','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA MERCED','90','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MONTEALTO','91','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VILLA ALARIFE','92','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CLARETIANO','93','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ABRAHAM VALDELOMAR','94','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO EMILIO SOYER CABERO','95','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIOS','96','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MATEMÁTICO SANTÍSIMA MARÍA','97','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JESUS SALVADOR','98','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VILLA CARITASS','99','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL PILAR','100','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE LIMA','101','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN FELIPE','102','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA SALLE','103','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CARMELITAS','104','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ESPECIALES','105','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MIXTO SANTA TERESITA','106','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MÓNICA','107','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LEONARD EULER','108','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN PABLO','109','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA URSULA','110','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE Y REDENTOR','111','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PRESCOTT','112','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INTERNACIONAL','113','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ANGELA','114','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE SAN ISIDRO','115','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA REPARACION','116','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JESUS REPARADOR','117','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MI HOGAR Y ESCUELA','118','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SALCANTAY','119','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA RECOLETA','120','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA AUXILIADORA','121','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LICEO MONTERO','122','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTO REDENTOR','123','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ISABEL DE HUNGRIA','124','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ANDRES','125','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MAX UHLE','126','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO COOPERATIVO SAN FELIPE','127','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTO TOMAS DE AQUINO','128','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SRA DE LA CONSOLACION','129','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARCELINO CHAMPAGNAT','130','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL ROSARIO','131','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ANNIES SCHOOL','132','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SEÑOR DE LA MISERICORDIA','133','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SCM','134','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INGLES DE MUJERES MATER ADMIRABILIS','135','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ALBERTO BENJAMIN SIMPSONS','136','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO FAP QUIÑONES','137','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LORD BYRON','138','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARKHAM COLLEGE','139','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PERUANO ALEMAN BEATA IMELDA','140','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN LUIS','141','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CORAZÓN DE MARÍA','142','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO IEA MIRAFLORES','143','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ENRIQUE MEIGGS','144','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO','145','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO WINNETKA','146','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DOMINGO SAVIA','147','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO BRITANICO EUROPEO DUNALASTAIR','148','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO BARTOLOME HERRERA','149','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA DE LA GRACIA','150','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA','151','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE DE CHACLACAYO','152','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LICEO NAVAL JUAN FANNING GARCIA','153','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE','154','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO EL CARMELO','155','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN GABRIEL','156','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO UNIVERSO CHORRILLOS','157','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA INES','158','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INKA GAKUEN','159','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NIVEL A','160','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PARTICULAR CORAZON DE JESUS PIONERO','161','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CORAZON DE JESUS PIONERO DE LA CIENCIA','162','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JOSEPH AND MERY HIGH SCHOOL','163','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PERUANO CHINO JUAN 23','164','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ITALIANO ANTONIO RAIMUNDI','165','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO AURELIO MIROQUESADA','166','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SKINNER','167','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN AGUSTIN','168','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO YACHAYHUASI','169','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA TERESITA','170','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('INSTITUCION PARTICULAR DE LA CRUZ','171','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA ASUNCIÓN','172','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MONTERRICO CHRISTIAN SCHOOL','173','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO IEP SANTA ANITA','174','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO HECTOR DE CARDENAS','175','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO RAYMOND CLARK','176','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACRADO CORAZON DE BELEN','177','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO BRUNING','178','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LE D\'ALEMBERT','179','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN PEDRO','180','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO HANS CHRISTIAN ANDERSON','181','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO IEP ADVENTISTA MIRAFLORES','182','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LIBERTADOR SAN MARTIN','183','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ROBERT LETOURNEAU','184','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN MARCOS DE MONTERRICO','185','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JUAN ENRIQUE NEWMAN','186','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUEVO MUNDO','187','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VIRGEN DE LA ASUNCION','188','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO HORACIO PATIÑO','189','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ENRIQUE CAMINO BRENT','190','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DAVID AUSEBEL','191','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN RAFAEL','192','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MELVIN JHONS SAN LUIS','193','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CHARBEL','194','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PERPETUO SOCORRO DE TRUJILLO','195','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PERUANO CHINO DIEZ DE OCTUBRE','196','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('EVENTO SAN ISIDRO','197','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DIVINO REDENTOR','198','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CHRISTIAN SCHOOL','199','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PARROQUIAL SAN JASE','200','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARTER PURISIMA','201','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MATILE','202','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ANDREAX','203','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN IGNACIO DE LOYOLA','204','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS ARANCIBIA','205','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAINT GEORGES','206','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COEGIO MARIA E LAS MERCEDES','207','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA DE LAS MERCEDES','208','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA MOLINARI','209','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ALGARROBOS-CHICLAYO','210','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN AGUSTIN CHICLAYO','211','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ALTERNATIVOS TALENTOS TRU','212','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CLARETIANO TRU','213','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JOSE OBRERO TRU','214','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA INMACULADA TRU','215','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DE CIENCIAS LORD KELVIN TRU','216','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SIR ALEXANDER FLEMING TRU','217','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO DE PADUO','218','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MONTEALTO','219','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MANUEL PARDO CHICL','220','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTO TORIBIO DE MOGROVEJO CHICL','221','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CEIBOS','222','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PARROQUIAL SANTA ROSA DE LIMA','223','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NOE','224','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LORD KELVIN TRUJILLO','225','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTO TORIBIO DE MOGROVEJO TRU','226','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TALENTOS TRU','227','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VIRGEN DE FATIMA DE BARRANCO','228','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PITAGORAS','229','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SEÑOR DE LUREN','230','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MAGISTER','231','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN IGNACIO DE LOYOLA PIU','232','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA MONTESSORI PIU','233','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TURICARA PIU','234','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VALLESOL PIU','235','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA PIU','236','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INMACULADO HIGH SCHOOL','237','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO BADEM POWELL','238','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO EL PINAR HUARAZ','239','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JEAN PIAGET','240','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO FAP FRANCISCO SECADA VIGNETTA','241','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('CLEGIO HEMINGWAY','242','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO EL BUEN PASTOR','243','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACOS OLIVEROS INGENIEROS','244','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ACUARELA-CAJAMARCA','245','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTO SALVADOR','246','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('EVENTOS MONTERRICO','247','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SOPHIANUM','248','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO FRANCO PERUANO','249','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN VICENTE DE PAUL','250','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL BUEN CONSEJO','251','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VIRGEN DE LA INMACULADA','252','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN MARTIN DE PORRAS-SANTA ANITA','253','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO COMAS EL RETABLO','254','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCA SI','255','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCA MO','256','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCA SM','257','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCA VI','258','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO MARISTA','259','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA MERCED SUR','260','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS LURIN','261','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO  Institucion Educativa Particular De La Cruz','262','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ENRIQUE NAPOLEON','263','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA TERECITAAA','264','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS PUENTE PIEDRA','265','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS VENTANILLA','266','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CEGNE ANDARES','267','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN FRANCISCO DE SALES','268','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA MARIA DE LOS CEDROS','269','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS LA VICTORIA','270','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRENTO COLONIAL','271','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO SALAVERRY','272','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ISSAC NEWTON','273','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO HOSANNA','274','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO BERKELEY SCHOOL','275','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SOR ANA DE LOS ANGELES','276','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ASOCIACION EDUCATIVA HOGAR Y ESCUELA','277','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CEGNE SANTA ANITA','278','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PUNTA ARENAS','279','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA EUFRASIA','280','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO CIPRECES','281','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA FE DE MARIA','282','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SEBASTIAN SALAZAR BONDY','283','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRUZ SACO NARANJAL','284','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA GORETI','285','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TORIBIO LUZURIAGA','286','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MATER CHRISTI','287','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL CARMEN','288','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JUAN BAUTISTA LA SALLE','289','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA MERCED SEDE CENTRAL','290','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS MONTESORI','291','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PASCUAL SACO OLIVEROS','292','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA RECONCILIACIÓN','293','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TECNIMEDIA CEPEBAN','294','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PARROQUIAL MARIA DE LA PROVIDENCIA','295','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CLARA COGORNO DE COGORNO','296','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JUAN DE BARRANCO','297','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO AMERICA','298','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MIGUEL ANGEL BUONARROTI','299','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACRADOS CORAZONES','300','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA VIRGEN DE LA PUERTA','301','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CORPORACION EDUCTIVA  CORAZON DE JESUS','302','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA PARADO DE BELLIDO','303','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MANUEL POLO JIMENEZ','304','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTO VICTORIOSO','305','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ATENEO DE LA MOLINA','306','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JESUALDO','307','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS VILLA EL SALVADOR','308','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO HIPOLITO UNANUE','309','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ADAM SMITH','310','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA CASA DE CARTON','311','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA REICHE','312','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO STEPHEN HAWKING','313','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ROSA DE SANTA MARIA','314','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LOS PEREGRINOS','315','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO GRUPO B','316','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA TRINIDAD','317','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PARTICULAR DE JESUS','318','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CESAR VALLEJO','319','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA UNION','320','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ANGELES DE LA PAZ','321','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SALESIANO SANTA ROSA','322','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MONTESSORI','323','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('Colegio GAF','324','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTO REY TACNA','325','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA INMACULADA CALIFORNIA','326','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL PERPETUO SOCORRO','327','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS ATE','328','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS PRO','329','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LA MOLINA CHRISTIAN','330','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACRADO CORAZON DE LA MOLINA','331','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO AMERICA DEL CALLAO','332','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LICEO NAVAL GERMAN ASTETE','333','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACRADO CORAZON','334','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE LA MERCED ATE','335','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE CHOSICA','336','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JOSEPH AND MERY HIGH SCHOOL','337','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MI JESUS','338','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ALBERT EINSTEIN','339','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO LOS LIERTADORES','340','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PITAGORAS NUEVO SAN JUAN','341','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CARLOS LISSON','342','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO REINA DE LOS ANGELES','343','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JESUS Y REDENTOR','344','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ANGELA MERICI','345','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL CALVO','346','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL BRITTO','347','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL TOCHE','348','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL CAMACHO','349','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL COPPOLA','350','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('ASESORIA VOCACIONAL VIZCARDO','351','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DIVINA TRINIDAD','352','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO IRMA DOLORES','353','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTINA ANNIE SOPPER-MOYOBAMBA','354','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA DE NAZARET-CAJAMARCA','355','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN JUAN BAUTISTA-PUNO','356','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SIMON BOLIVAR -TARAPOTO','357','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRENTO ESCARDO','358','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DEL CONSUELO -SAN MIGUEL','359','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO NUESTRA SEÑORA DE FATIMA','360','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SOR ANA DE LOS ANGELES SJL','361','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ANDRES BELLOS','362','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CRISTIANO PIONERO','363','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INTERNACIONAL DE LIMA SURCO','364','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ROSA DE LIMA SAN BORJA','365','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JUAN INGUNZA VALDIVIA','366','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA MARIA DE ICA','367','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTA ANA SAN MIGUEL','368','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PIEDRA HERRERA LUCERO DEL CARMEN','369','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO JUAN LINARES ROJAS','370','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CIENCIAS DE TARAPOTO','371','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO ANDRE MALRAUX','372','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN ANTONIO DE HUAMANGA -AYACUCHO','373','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTO DOMINGO EL PREDICADOR','374','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VILLA JARDIN','375','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SANTISIMA CRUZ','376','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DIVINA PROVIDENCIA','377','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SACO OLIVEROS SEDE SORIA','378','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MONSENOR MARCOS LIBARDONI','379','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO CEP UNI','380','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN RICARDO','381','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('UNIVERSIDAD ANDRES BELLO CHILE','382','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DALTON','383','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRENER','384','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PALESTRA','385','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SEBASTIAN SALAZAR BONDI -SANTA ANITA','386','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PERUANO CHINO CHICLAY','387','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO GEORGE COLLEGE','388','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO VICTORIA BARCIA','389','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO MARIA AUXILIADORA- CALLAO','390','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO SAN FRANCISCO - SAN BORJA','391','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO DOMINGO FAUSTINO SARM-PUENTE PIEDRA','392','1');

INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA VILLA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SURCO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA LOS OLIVOS','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CARABAYLLO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('INNOVA CANTA CALLAO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SAN MIGUEL','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA VILLA EL SALVADOR','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CALLAO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SMP','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA RIMAC','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA LOS FAISANES','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA VITARTE','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SCHOOL CERCADO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA COMAS','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SANTO TORIBIO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CANTO GRANDE','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHINCHA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA TACNA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA HUACHO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA BUSTAMANTE Y RIVERO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CAMPOY','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA PIURA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHIMBOTE','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SANTA CLARA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA LA CAMPIÑA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA PURUCHURO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SAENZ PEÑA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHICLAYO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA ICA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHACLACAYO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA AREQUIPA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('INNOVA PUEBLO LIBRE','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA LA PAZ','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA TRUJILLO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('INNOVA VILLASOL','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA HUANCAYO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('INNOVA CHORRILLOS LADRAS DE VILLA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHORRILLOS UNIVERSO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA AMBROSIO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('Colegio Innova Rimac SC','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA BERTELLO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SCHOOLS CUSCO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA AV, PERU','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA ARABISCOS','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SJL','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SJM','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SCHOOLS','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('INNOVA CERRO COLORADO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA AREQ-SACHACA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CALLAO-LEMOS','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CARABAYLLO -ENACE','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CARABAYLLO-SAN ANTONIO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHORRILLOS -VILLA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA CHORRILLOS-HORIZONTES','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA COMAS-CONDORCANQUI','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA RETABLO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA LOS OLIVOS VILLA SOL','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA  LOS OLIVOS SANTA ANITA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA MOQUEGUA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA PUCALPA','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA SJL EL SOL','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA TARAPOTO','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA TRUJILLO EL GOLF','393','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO INNOVA TRUJILLO SANTA','393','1');


INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE SANTA ANITA','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE LA MOLINA','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE VILLA EL SALVADOR','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE CHORRILLOS','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE SALAVERRY','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE SAN ISIDRO','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE TRU','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRILCE CHICLAYO','394','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO TRENTO TRILCE','394','1');


INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER PUENTE PIEDRA','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER JESUS MARIA','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER VILLA EL SALVADOR','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER IZAGUIRRE','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER SAN ISIDRO','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER CARABAYLLO','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('Colegio Pamer Contisuyo','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER LINCE','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER CAJAHUAMAN','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER CHORRILLOS','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER MAGDALENA','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER COMAS','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER LAS ARENAS -PIURA','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER REPUBLICA DE CHILE','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER BARRANCO','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER LA LIBERTAD','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER DURAZNOS','395','1');
INSERT INTO `empresa_sucursal` (`nombre`,`empresa_id`,`insert_user_id`) VALUES ('COLEGIO PAMER SALAMANCA','395','1');



